with source as (

    select * from {{ source('afe_execute', 'EX_AFE') }}

),

renamed as (
    SELECT
        document_id AS "Document ID",
        accrual_doc AS "Accrual Doc",
        actual_doc AS "Actual Doc",
        afelink_tracking_id AS "Afelink Tracking ID",
        afenumber_doc AS "AFENumber Doc",
        approved_gross_estimate AS "Approved Gross Estimate",
        approved_net_estimate AS "Approved Net Estimate",
        base_creation_date AS "Base Creation Date",
        budget_manager AS "Budget Manager",
        budget_year AS "Budget Year",
        chain_guid AS "Chain GUID",
        chain_version AS "Chain Version",
        closed AS "Closed",
        closed_date AS "Closed Date",
        closed_reason AS "Closed Reason",
        closed_user AS "Closed User",
        completed AS "Completed",
        corr_number AS "Corr Number",
        creation_date AS "Creation Date",
        creator AS "Creator",
        currency_code AS "Currency Code",
        description AS "Description",
        end_date AS "End Date",
        estimate_conversion_date AS "Estimate Conversion Date",
        external_justification AS "External Justification",
        fasttrack AS "Fasttrack",
        fieldcost_doc AS "Fieldcost Doc",
        full_approval_date AS "Full Approval Date",
        internal_approval_date AS "Internal Approval Date",
        internal_justification AS "Internal Justification",
        is_removed_version AS "Is Removed Version",
        legacy_afeid AS "Legacy AFEID",
        legacy_chainid AS "Legacy ChainID",
        next_approving_positions AS "Next Approving Positions",
        next_reviewing_positions AS "Next Reviewing Positions",
        operating_company AS "Operating Company",
        op_notice AS "OP Notice",
        our_wi AS "Our WI",
        outside_afenumber AS "Outside AFENumber",
        owner AS "Owner",
        parent_company AS "Parent Company",
        parent_rtd AS "Parent RTD",
        parent_rtx AS "Parent RTX",
        released_date AS "Released Date",
        release_comment AS "Release Comment",
        release_user AS "Release User",
        required_by_date AS "Required By Date",
        review_completed_date AS "Review Completed Date",
        rev_number AS "Rev Number",
        rev_sup_mode AS "Rev Sup Mode",
        routed_comment AS "Routed Comment",
        routed_date AS "Routed Date",
        routed_user AS "Routed User",
        silent_partner_mode AS "Silent Partner Mode",
        start_date AS "Start Date",
        status AS "Status",
        status_desc AS "Status Desc",
        superseded_date AS "Superseded Date",
        superseded_status AS "Superseded Status",
        superseded_status_desc AS "Superseded Status Desc",
        supplemental_gross_estimate AS "Supplemental Gross Estimate",
        supplemental_net_estimate AS "Supplemental Net Estimate",
        sup_number AS "Sup Number",
        total_gross_estimate AS "Total Gross Estimate",
        total_net_estimate AS "Total Net Estimate",
        version_string AS "Version String",
        vn_cost_type AS "VN Cost Type",
        vn_entity AS "VN Entity",
        vn_plan AS "VN Plan",
        vn_rescat AS "VN Rescat",
        vn_scenario AS "VN Scenario",
        well_list_title AS "Well List Title",
        well_reporting_identifier AS "Well Reporting Identifier",
        _author AS "Author",
        _date AS "Date",
        _deleted AS "Deleted",
        _version AS "Version",
        "_meta/op" AS "Meta Op",
        flow_published_at AS "Flow Published At",
        flow_document AS "Flow Document"
    FROM source
)

select *
from source

        