version: 2

models:
  - name: fct_ar_aging_detail
    description: >
      Transaction-level AR aging fact. One row per AR transaction (invoice, payment,
      adjustment, or netting). Replaces fct_ar_aging (retired 2026-02-18).

      Includes is_invoice_posted and is_voucher_posted flags enabling pre-JIB
      analysis (unposted invoices) alongside standard posted AR aging. The parent
      invoice's remaining_balance and include_record are repeated on every
      transaction row for consumer convenience — no additional join needed.

      Use cases:
      - Drill-down to individual transactions for an invoice
      - Pre-JIB preview: WHERE is_invoice_posted = false
      - Posted AR aging: WHERE is_invoice_posted = true AND include_record = 1
    columns:
      - name: invoice_id
        description: FK to stg_oda__arinvoice_v2 — identifies the parent invoice
        data_tests:
          - not_null
      - name: transaction_source
        description: "One of: invoice, payment, adjustment, netting"
        data_tests:
          - not_null
      - name: is_invoice_posted
        description: True when the parent invoice is posted in ODA
        data_tests:
          - not_null
      - name: is_voucher_posted
        description: True when the voucher for this specific transaction is posted
      - name: include_record
        description: >
          1 when remaining_balance != 0 AND exclude_pair = 0. Filter on this for
          actionable outstanding AR transactions.
        data_tests:
          - not_null
      - name: remaining_balance
        description: Total remaining balance on the parent invoice (all transactions, posted and unposted)
        data_tests:
          - not_null:
              config:
                severity: warn
      - name: remaining_balance_posted
        description: >
          Balance comprising only posted invoice amount and posted transaction components.
          NOTE: remaining_balance_posted + remaining_balance_unposted does NOT equal
          remaining_balance when transactions span posted/unposted boundaries (e.g. a
          payment applied to a posted invoice before it posts). These are independent
          views, not a partition of remaining_balance.
      - name: remaining_balance_unposted
        description: >
          Balance comprising only unposted invoice amount and unposted transaction components.
          See remaining_balance_posted for important note about additivity.
      - name: exclude_pair
        description: "1 when the parent invoice is part of an advance/closeout pair"
      - name: balance_due
        description: Transaction amount (positive for invoices, negative for payments/netting)

  - name: fct_ar_aging_summary
    description: >
      Invoice-level AR aging summary with standard aging bucket columns.
      One row per invoice. Replaces fct_ar_aging (retired 2026-02-18).

      Aging bucket definition (based on DATEDIFF(day, invoice_date, CURRENT_DATE())):
      - current_balance: <= 0 days (future-dated or today)
      - balance_1_30_days: 1-30 days past due
      - balance_31_60_days: 31-60 days past due
      - balance_61_90_days: 61-90 days past due
      - balance_90_plus_days: > 90 days past due

      Pre-JIB unposted invoices with future billing dates land in current_balance.
      This is intentional — they represent upcoming billing.

      Use cases:
      - Standard AR aging report: WHERE include_record = 1
      - Posted-only aging: WHERE is_invoice_posted = true AND include_record = 1
      - Pre-JIB treasury preview: WHERE is_invoice_posted = false
    data_tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "remaining_balance is not null"
          config:
            severity: error
            # error_msg removed — not a valid dbt test config key in dbt-fusion
    columns:
      - name: invoice_id
        description: PK — unique per invoice
        data_tests:
          - unique
          - not_null
      - name: is_invoice_posted
        description: True when the invoice is posted in ODA
        data_tests:
          - not_null
      - name: is_voucher_posted
        description: True when the invoice's voucher is posted
      - name: remaining_balance
        description: >
          Invoice amount + payments + adjustments + netting (additive formula,
          E2E validated against Snowflake data). Negative = credit balance.
        data_tests:
          - not_null
      - name: remaining_balance_posted
        description: >
          Balance comprising only posted invoice amount and posted transaction components.
          Does NOT partition remaining_balance — cross-posted transactions make the two
          split columns non-additive. Use as an independent view, not a decomposition.
      - name: remaining_balance_unposted
        description: >
          Balance comprising only unposted invoice amount and unposted transaction components.
          See remaining_balance_posted for important note about additivity.
      - name: include_record
        description: >
          1 when remaining_balance != 0 AND exclude_pair = 0.
          Bucket columns (current_balance, balance_1_30_days, etc.) populate for ALL invoices
          regardless of this flag. Always filter WHERE include_record = 1 before summing buckets.
        data_tests:
          - not_null
      - name: exclude_pair
        description: "1 when invoice is part of an advance/closeout pair (excluded from aging)"
      - name: days_past_due
        description: DATEDIFF(day, invoice_date, CURRENT_DATE()). Negative for future-dated invoices.
      - name: current_balance
        description: Balance for invoices not yet past due (days_past_due <= 0)
      - name: balance_1_30_days
        description: Balance for invoices 1-30 days past due (BETWEEN 1 AND 30, inclusive)
      - name: balance_31_60_days
        description: Balance for invoices 31-60 days past due
      - name: balance_61_90_days
        description: Balance for invoices 61-90 days past due
      - name: balance_90_plus_days
        description: Balance for invoices more than 90 days past due (> 90, no upper bound)

  - name: dim_wells
    description: >
      Well dimension for LOS reporting and Cortex Analyst. One row per ODA well.

      ⚠️  This is a VIEW over well_360 (converted 2026-02-19). Do not alter column names —
      the Cortex Analyst LOS semantic model (LOS_SEMANTIC_MODEL-2.yaml) joins on WELL_ID
      and references many columns from this view.

      Grain: one row per well with an ODA numeric ID (oda_well_id IS NOT NULL in well_360).
      Join key for Cortex: FCT_LOS.WELL_ID = DIM_WELLS.WELL_ID (ODA internal numeric ID).
    columns:
      - name: well_id
        description: ODA internal numeric well ID. Primary key for Cortex Analyst joins (maps to oda_well_id in well_360).
        data_tests:
          - unique
          - not_null
      - name: well_code
        description: ODA cost center code (maps to cost_center_number in well_360).
      - name: well_name
        description: Golden well name from well_360.
      - name: api_number
        description: API-10 identifier (maps to api_10 in well_360).
      - name: basin_name
        description: Formentera operational basin classification (Permian Basin, Eagle Ford, SCOOP/STACK, etc.).
      - name: state_name
        description: Standardized 2-char state abbreviation (maps to state in well_360).
      - name: county_name
        description: Standardized county name in InitCap format (maps to county in well_360).
      - name: op_ref
        description: Standardized operated status string (OPERATED, NON-OPERATED, CONTRACT OPERATED, NON-WELL, etc.).
      - name: is_operated
        description: True when Formentera operates this well.
      - name: is_revenue_generating
        description: True when well is actively producing revenue (not held or suspended).
      - name: is_stripper_well
        description: True when ODA classifies as a stripper well.
      - name: is_well
        description: True when cost_center_type_name = 'Well' (excludes facilities and non-well cost centers).
      - name: activity_status
        description: "Human-friendly well status: Producing, Shut In, Plugged & Abandoned, Temporarily Abandoned, Planned, Injector, Sold, Other."
      - name: well_type
        description: Well type from name patterns (Horizontal, SWD, Injector, Unit Well, Vertical/Conventional, Other). Maps to well_type_oda in well_360.
      - name: search_key
        description: UF-SEARCH KEY userfield — used as GL reporting cross-reference key.
      - name: pv_field
        description: UF-PV FIELD userfield — ProdView field classification.
      - name: operating_group_name
        description: ODA operating group name for regional reporting.
      - name: cost_center_type_name
        description: ODA cost center type name (always 'Well' for rows in this view).
      - name: spud_date
        description: Spud date from well_360 (WellView or Enverus).
      - name: first_production_date
        description: Earliest first production date from well_360.
      - name: shut_in_date
        description: Date well was shut in per ODA.
      - name: inactive_date
        description: Date well became inactive per ODA.
      - name: _refreshed_at
        description: Timestamp when this row was generated (current_timestamp() at query time — this is a view).

  - name: wells
    description: Unified wells data combining project wells and company wells.
    columns:
      - name: well_id
        description: Unique identifier for the well.
        data_tests:
          - unique
          - not_null
