case upper(trim(state_value))
    when 'ALABAMA' then 'AL'
    when 'ALASKA' then 'AK'
    when 'ARIZONA' then 'AZ'
    when 'ARKANSAS' then 'AR'
    when 'CALIFORNIA' then 'CA'
    when 'COLORADO' then 'CO'
    when 'CONNECTICUT' then 'CT'
    when 'DELAWARE' then 'DE'
    when 'FLORIDA' then 'FL'
    when 'GEORGIA' then 'GA'
    when 'HAWAII' then 'HI'
    when 'IDAHO' then 'ID'
    when 'ILLINOIS' then 'IL'
    when 'INDIANA' then 'IN'
    when 'IOWA' then 'IA'
    when 'KANSAS' then 'KS'
    when 'KENTUCKY' then 'KY'
    when 'LOUISIANA' then 'LA'
    when 'MAINE' then 'ME'
    when 'MARYLAND' then 'MD'
    when 'MASSACHUSETTS' then 'MA'
    when 'MICHIGAN' then 'MI'
    when 'MINNESOTA' then 'MN'
    when 'MISSISSIPPI' then 'MS'
    when 'MISSOURI' then 'MO'
    when 'MONTANA' then 'MT'
    when 'NEBRASKA' then 'NE'
    when 'NEVADA' then 'NV'
    when 'NEW HAMPSHIRE' then 'NH'
    when 'NEW JERSEY' then 'NJ'
    when 'NEW MEXICO' then 'NM'
    when 'NEW YORK' then 'NY'
    when 'NORTH CAROLINA' then 'NC'
    when 'NORTH DAKOTA' then 'ND'
    when 'OHIO' then 'OH'
    when 'OKLAHOMA' then 'OK'
    when 'OREGON' then 'OR'
    when 'PENNSYLVANIA' then 'PA'
    when 'RHODE ISLAND' then 'RI'
    when 'SOUTH CAROLINA' then 'SC'
    when 'SOUTH DAKOTA' then 'SD'
    when 'TENNESSEE' then 'TN'
    when 'TEXAS' then 'TX'
    when 'UTAH' then 'UT'
    when 'VERMONT' then 'VT'
    when 'VIRGINIA' then 'VA'
    when 'WASHINGTON' then 'WA'
    when 'WEST VIRGINIA' then 'WV'
    when 'WISCONSIN' then 'WI'
    when 'WYOMING' then 'WY'
    else upper(trim(state_value))
end
