name: 'formentera_partners_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Use custom schema naming
require-dbt-version: ">=1.0.0"

# Configuring models
models:
  formentera_partners_analytics:
    # Config applied to all models
    +materialized: view  # Default materialization

    # Source/Raw models - minimal transformations
    src:
      +database: FO_RAW_DB
      +schema: src
      +materialized: view

    # Staging models - cleaned data, 1:1 with source
    staging:
      +database: FO_STAGE_DB
      +materialized: view
      
      # Combo Curve staging models
      combo_curve:
        +schema: stg_combo_curve
        +materialized: view

      # Hubspot staging models 
      hubspot:
        +schema: stg_hubspot
        +materialized: view

    # Intermediate models - business logic layers
    intermediate:
      +database: FO_STAGE_DB
      +schema: intermediate
      +materialized: ephemeral
      +tags: ["intermediate"]

    # Mart models - business-facing data models
    marts:
      +database: FO_PRODUCTION_DB
      +schema: marts
      +materialized: table
      +tags: ["marts"]