name: formentera_analytics
version: "1.0.0"
config-version: 2
require-dbt-version: ">=1.0.0"

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ dbt_snow_mask.apply_masking_policy('sources') if target.name in ['prod'] else '' }}"

models:
  +post-hook:
    - "{{ dbt_snow_mask.apply_masking_policy('models') }}"

  elementary:
    ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"
    ## To disable elementary for dev, uncomment this:
    # enabled: "{{ target.name in ['prod','analytics'] }}"

  formentera_analytics:
    +materialized: view
    +copy_grants: true

    # Formentera Operations (Tenant 1)
    operations:

      # Staging models - cleaned data, 1:1 with source
      staging:
        +database: FO_STAGE_DB
        combo_curve: {+schema: "stg_combo_curve"}
        hubspot: {+schema: "stg_hubspot"}
        oda: {+schema: "stg_oda"}
        prodview: {+schema: "stg_prodview"}
        wellview: {+schema: "stg_wellview"}
        enverus: {+schema: "stg_enverus"}
        procount: {+schema: "stg_procount"}

      # Intermediate models - business logic layers
      intermediate:
        +database: FO_STAGE_DB
        +schema: intermediate
        +materialized: ephemeral
        +tags: ["intermediate", "fo"]

      # Mart models - business-facing data models
      marts:
        +database: FO_PRODUCTION_DB
        +schema: marts
        +materialized: table
        +tags: ["marts", "fo"]
        griffin:
          +schema: griffin
          +materialized: table

      # Applications models - application-specific data models
      applications:
        +database: FORMENTERA_OPS_DB
        wiserock:
          +schema: wiserock
          +materialized: table

    # Formentera Partners (Tenant 2)
    partners:

      # Staging models - cleaned data, 1:1 with source
      staging:
        +database: FP_STAGE_DB

      # Intermediate models - business logic layers
      intermediate:
        +database: FP_STAGE_DB
        +schema: intermediate
        +materialized: ephemeral
        +tags: ["intermediate", "fp"]

      # Mart models - business-facing data models
      marts:
        +database: FP_PRODUCTION_DB
        +schema: marts
        +materialized: table
        +tags: ["marts", "fp"]

vars:
  # https://github.com/Formentera-Operations/snowflake-infrastructure/blob/f10d9a849c3bfcb7df91acb3af10fd3407bb2703/snowflake/warehouse_services.tf
  available_warehouse_sizes: ["XS", "S", "M"]
  enable_dynamic_warehouse: true

  ###  dbt-snow-mask  ###
  use_force_applying_masking_policy: "True"
  create_masking_policy_schema: "False"
  use_common_masking_policy_db: "True"
  # https://github.com/Formentera-Operations/snowflake-infrastructure/blob/f10d9a849c3bfcb7df91acb3af10fd3407bb2703/snowflake/masking_policy.tf
  common_masking_policy_db: "SECURITY_DB"
  common_masking_policy_schema: "MASKING_POLICIES"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false
  source_freshness_run_project_hooks: true
  require_generic_test_arguments_property: true
