version: 2

models:
  - name: stg_enverus__wells
    description: >
      Master well table containing core well information including location,
      operator classification, and key identifiers. Central table for joining
      to other well-related data.
      
      Keeps only the most recent record for each well by removing deleted
      records.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - well_id
            - completion_id
    columns:
      - name: well_id
        description: Unique identifier for the well.
        data_tests:
          - not_null
      - name: completion_id
        description: Completion identifier for the well.
        data_tests:
          - not_null
