version: 2

models:
  - name: stg_oda__account_types
    description: |
      Staging model for Chart of Accounts Type classifications from Quorum OnDemand Accounting.
      This model contains the high-level categorization of accounts.
    columns:
      - name: account_type_id
        description: Unique identifier for the account type
        data_tests:
          - unique
          - not_null

      - name: type_code
        description: Code used to identify the account type
        data_tests:
          - unique
          - not_null

      - name: type_name
        description: Short name of the account type
        data_tests:
          - not_null

      - name: type_full_name
        description: Full descriptive name of the account type
        data_tests:
          - not_null

      - name: record_insert_date
        description: Timestamp when the record was first inserted
        data_tests:
          - not_null

      - name: record_update_date
        description: Timestamp when the record was last updated

  - name: stg_oda__gl
    config:
      meta:
        elementary:
          timestamp_column: _flow_published_at
    description: |
      Staging model for General Ledger entries from Quorum OnDemand Accounting.
      This is a critical table that contains all financial transactions across the organization, 
      including journal entries, accounts payable/receivable transactions, and automated postings.
      The model standardizes raw GL data by:
      - Converting status flags to boolean
      - Standardizing date formats
      - Handling NULL and empty descriptions
      - Standardizing currency values with explicit decimal casting
      - Converting raw column names to snake_case
    data_tests:
      # 1. Monitor daily volume - know if data stops flowing
      - elementary.volume_anomalies:
          arguments:
            time_bucket:
              period: day
              count: 1
            where_expression: "journal_date >= current_date - 30"  # Only look at recent data
            anomaly_sensitivity: 4  # Start less sensitive to reduce noise

      # 2. Check data freshness - ensure pipeline is working
      - elementary.freshness_anomalies:  # Fixed: removed extra 's'
          arguments:
            anomaly_sensitivity: 3

      # 3. Monitor the most critical column - money
      - elementary.column_anomalies:
          column_name: net_value
          arguments:
            column_anomalies:
              - sum  # Total money flow
              - zero_count  # Unusual number of zero amounts
            where_expression: "is_posted = true and journal_date >= current_date - 14"

    columns:
      - name: id
        description: Unique identifier for each GL entry
        data_tests:
          - unique
          - not_null

      - name: company_id
        description: Identifier for the company associated with the transaction
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref("stg_oda__company_v2")
                field: id

      - name: account_id
        description: Foreign key to the Chart of Accounts
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref("stg_oda__account_v2")
                field: account_id

      - name: journal_date_key
        description: Date key for the journal entry, used for date-based lookups
        data_tests:
          - not_null

      - name: journal_date
        description: Date when the transaction was recorded in the general ledger
        data_tests:
          - not_null

      - name: accrual_date
        description: Date when the transaction should be recognized for accrual accounting purposes

      - name: cash_date
        description: Date when the cash transaction occurred or is expected to occur

      - name: description
        description: Detailed description of the transaction, standardized to 'No Description' when empty or NULL
        data_tests:
          - not_null  # Added because we're defaulting empty values
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              arguments:
                min_value: 1
                max_value: 1000

      - name: gross_value
        description: Original transaction amount before any allocations or splits
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: -10000000000  # Extended based on actual data
                max_value: 10000000000

      - name: net_value
        description: Final transaction amount after allocations or splits
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: -10000000000  # Extended based on actual data
                max_value: 10000000000

      - name: currency_id
        description: Currency code for the transaction
        data_tests:
          - not_null

      - name: is_posted
        description: Indicates if the transaction has been posted to the general ledger
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

      - name: is_reconciled
        description: Indicates if the transaction has been reconciled
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

      - name: source_module
        description: System module that generated the transaction. Distribution as of analysis - GL (62M), AP (48.6M), Revenue (40.3M), AR (185K)
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["GL", "AP", "Revenue", "AR"]

      - name: source_module_code
        description: Code representing the source module
        data_tests:
          - relationships:
              arguments:
                to: ref("stg_oda__source_module")  # Assuming this reference exists
                field: code

      - name: afe_id
        description: Reference to Authorization for Expenditure
        data_tests:
          - relationships:
              arguments:
                to: ref("stg_oda__afe_v2")
                field: id

      - name: created_at
        description: Timestamp when the record was created
        data_tests:
          - not_null

      - name: _flow_published_at
        description: Timestamp when the record was published to the data flow
        data_tests:
          - not_null

  - name: stg_oda__account_sub_types
    description: |
      Staging model for Chart of Accounts Subtype classifications from Quorum OnDemand Accounting.
      This model contains the detailed subcategorization of accounts within each account type.
    columns:
      - name: account_subtype_id
        description: Unique identifier for the account subtype
        data_tests:
          - unique
          - not_null

      - name: account_type_id
        description: Foreign key to the parent account type
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref("stg_oda__account_types")
                field: account_type_id

      - name: subtype_code
        description: Code used to identify the account subtype
        data_tests:
          - unique
          - not_null

      - name: subtype_name
        description: Short name of the account subtype
        data_tests:
          - not_null

      - name: subtype_full_name
        description: Full descriptive name of the account subtype
        data_tests:
          - not_null

      - name: normally_debit
        description: Flag indicating if accounts of this subtype normally have a debit balance
        data_tests:
          - not_null

      - name: record_insert_date
        description: Timestamp when the record was first inserted
        data_tests:
          - not_null

      - name: record_update_date
        description: Timestamp when the record was last updated
  - name: stg_oda__account_v2
    description: |
      Staging model for Chart of Accounts data from Quorum OnDemand Accounting.
      This model standardizes column names and structures account information for downstream consumption.
    columns:
      - name: account_id
        description: Unique identifier for the account
        data_tests:
          - unique
          - not_null

      - name: account_v2_identity
        description: Legacy identity key for the account

      - name: n_id
        description: Numeric identifier from source system

      - name: account_code
        description: Account code used for identification
        data_tests:
          - not_null
          - unique

      - name: account_name
        description: Short name of the account
        data_tests:
          - not_null

      - name: account_full_name
        description: Full descriptive name of the account
        data_tests:
          - not_null

      - name: main_account
        description: Main account segment

      - name: sub_account
        description: Sub account segment

      - name: account_sort
        description: Sorting value for the account
        data_tests:
          - not_null

      - name: key_sort
        description: Additional sorting key for the account

      - name: account_type_id
        description: Foreign key to account type
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref("stg_oda__account_types")
                field: account_type_id

      - name: account_subtype_id
        description: Foreign key to account subtype
        data_tests:
          - relationships:
              arguments:
                to: ref("stg_oda__account_sub_types")
                field: account_subtype_id

      - name: is_active
        description: Flag indicating if the account is currently active
        data_tests:
          - not_null

      - name: is_normally_debit
        description: Flag indicating if the account normally has a debit balance
        data_tests:
          - not_null

      - name: is_accrual
        description: Derived flag indicating if account name contains 'accru'

      - name: is_summarize_in_gl_reports
        description: Flag indicating if account should be summarized in GL reports
        data_tests:
          - not_null

      - name: is_summarize_in_jib_invoice
        description: Flag indicating if account should be summarized in JIB invoices
        data_tests:
          - not_null

      - name: jib_summary_id
        description: JIB summary identifier for account grouping

      - name: is_bank_recon_performed
        description: Flag indicating if bank reconciliation is performed for this account
        data_tests:
          - not_null

      - name: changed_since_printed
        description: Flag/counter for changes since last print

      - name: is_generate_fixed_asset_candidates
        description: Flag indicating if fixed asset candidates should be generated

      - name: is_remeasure_at_current
        description: Flag for currency remeasurement at current rate

      - name: is_translate_at_current
        description: Flag for currency translation at current rate

      - name: afe_usage_type_id
        description: Usage type for AFE (Authorization for Expenditure) entries

      - name: alternate_reference_usage_type_id
        description: Usage type for alternate reference entries

      - name: entry_classification_usage_type_id
        description: Usage type for entry classification

      - name: expense_distribution_usage_type_id
        description: Usage type for expense distribution

      - name: manual_entry_usage_type_id
        description: Usage type for manual entries

      - name: well_usage_type_id
        description: Usage type for well-related entries

      - name: location_grouping_id
        description: Location grouping identifier

      - name: last_change_code
        description: Code indicating last type of change

      - name: created_at
        description: Timestamp when the record was created in source system
        data_tests:
          - not_null

      - name: updated_at
        description: Timestamp when the record was last updated in source system

      - name: flow_published_at
        description: Timestamp when the record was published to the data flow
        data_tests:
          - not_null

      - name: _loaded_at
        description: Timestamp when record was loaded by dbt
        data_tests:
          - not_null
  
