version: 2

models:
  - name: stg_oda__gl
    config:
      meta:
        elementary:
          timestamp_column: _flow_published_at
    description: |
      Staging model for General Ledger entries from Quorum OnDemand Accounting.
      This is a critical table that contains all financial transactions across the organization,
      including journal entries, accounts payable/receivable transactions, and automated postings.
      The model standardizes raw GL data by:
      - Converting status flags to boolean
      - Standardizing date formats
      - Handling NULL and empty descriptions
      - Standardizing currency values with explicit decimal casting
      - Converting raw column names to snake_case
    data_tests:
      # 1. Monitor daily volume - know if data stops flowing
      - elementary.volume_anomalies:
          arguments:
            time_bucket:
              period: day
              count: 1
            where_expression: "journal_date >= current_date - 30"  # Only look at recent data
            anomaly_sensitivity: 4  # Start less sensitive to reduce noise

      # 2. Check data freshness - ensure pipeline is working
      - elementary.freshness_anomalies:  # Fixed: removed extra 's'
          arguments:
            anomaly_sensitivity: 3

      # 3. Monitor the most critical column - money
      - elementary.column_anomalies:
          column_name: net_value
          arguments:
            column_anomalies:
              - sum  # Total money flow
              - zero_count  # Unusual number of zero amounts
            where_expression: "is_posted = true and journal_date >= current_date - 14"

    columns:
      - name: id
        description: Unique identifier for each GL entry
        data_tests:
          - unique
          - not_null

      - name: company_id
        description: Identifier for the company associated with the transaction
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref("stg_oda__company_v2")
                field: id

      - name: account_id
        description: Foreign key to the Chart of Accounts
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref("stg_oda__account_v2")
                field: id
              config:
                severity: warn

      - name: journal_date_key
        description: Date key for the journal entry, used for date-based lookups
        data_tests:
          - not_null

      - name: journal_date
        description: Date when the transaction was recorded in the general ledger
        data_tests:
          - not_null

      - name: accrual_date
        description: Date when the transaction should be recognized for accrual accounting purposes

      - name: cash_date
        description: Date when the cash transaction occurred or is expected to occur

      - name: description
        description: Detailed description of the transaction, standardized to 'No Description' when empty or NULL
        data_tests:
          - not_null  # Added because we're defaulting empty values
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              arguments:
                min_value: 1
                max_value: 1000

      - name: gross_value
        description: Original transaction amount before any allocations or splits
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: -10000000000  # Extended based on actual data
                max_value: 10000000000

      - name: net_value
        description: Final transaction amount after allocations or splits
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: -10000000000  # Extended based on actual data
                max_value: 10000000000

      - name: currency_id
        description: Currency code for the transaction
        data_tests:
          - not_null

      - name: is_posted
        description: Indicates if the transaction has been posted to the general ledger
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

      - name: is_reconciled
        description: Indicates if the transaction has been reconciled
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

      - name: source_module
        description: System module that generated the transaction. Distribution as of analysis - GL (62M), AP (48.6M), Revenue (40.3M), AR (185K)
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["GL", "AP", "Revenue", "AR"]

      - name: source_module_code
        description: Code representing the source module
        data_tests:
          - relationships:
              arguments:
                to: ref("stg_oda__source_module")  # Assuming this reference exists
                field: code

      - name: afe_id
        description: Reference to Authorization for Expenditure
        data_tests:
          - relationships:
              arguments:
                to: ref("stg_oda__afe_v2")
                field: id

      - name: created_at
        description: Timestamp when the record was created
        data_tests:
          - not_null

      - name: _flow_published_at
        description: Timestamp when the record was published to the data flow
        data_tests:
          - not_null
