version: 2

models:
  - name: stg_oda__account_types
    description: |
      Staging model for Chart of Accounts Type classifications from Quorum OnDemand Accounting.
      This model contains the high-level categorization of accounts.
    columns:
      - name: account_type_id
        description: Unique identifier for the account type
        tests:
          - unique
          - not_null

      - name: type_code
        description: Code used to identify the account type
        tests:
          - unique
          - not_null

      - name: type_name
        description: Short name of the account type
        tests:
          - not_null

      - name: type_full_name
        description: Full descriptive name of the account type
        tests:
          - not_null

      - name: record_insert_date
        description: Timestamp when the record was first inserted
        tests:
          - not_null

      - name: record_update_date
        description: Timestamp when the record was last updated

  - name: stg_oda__gl
    config: 
      elementary:
        timestamp_column: flow_published_at
    description: |
      Staging model for General Ledger entries from Quorum OnDemand Accounting.
      This is a critical table that contains all financial transactions across the organization, 
      including journal entries, accounts payable/receivable transactions, and automated postings.
      The model standardizes raw GL data by:
      - Converting status flags to boolean
      - Standardizing date formats
      - Handling NULL and empty descriptions
      - Standardizing currency values with explicit decimal casting
      - Converting raw column names to snake_case
    data_tests:
      # 1. Monitor daily volume - know if data stops flowing
      - elementary.volume_anomalies:
          time_bucket:
            period: day
            count: 1
          where_expression: "journal_date >= current_date - 30"  # Only look at recent data
          anomaly_sensitivity: 4  # Start less sensitive to reduce noise
          
      # 2. Check data freshness - ensure pipeline is working    
      - elementary.freshness_anomalies:  # Fixed: removed extra 's'
          anomaly_sensitivity: 3
      
      # 3. Monitor the most critical column - money
      - elementary.column_anomalies:
          column_name: net_value
          column_anomalies:
            - sum  # Total money flow
            - zero_count  # Unusual number of zero amounts
          where_expression: "is_posted = true and journal_date >= current_date - 14"
          
    columns:
      - name: id
        description: Unique identifier for each GL entry
        tests:
          - unique
          - not_null

      - name: company_id
        description: Identifier for the company associated with the transaction
        tests:
          - not_null
          - relationships:
              to: ref('stg_oda__company_v2')
              field: id

      - name: account_id
        description: Foreign key to the Chart of Accounts
        tests:
          - not_null
          - relationships:
              to: ref('stg_oda__account_v2')
              field: id

      - name: journal_date_key
        description: Date key for the journal entry, used for date-based lookups
        tests:
          - not_null
              
      - name: journal_date
        description: Date when the transaction was recorded in the general ledger
        tests:
          - not_null

      - name: accrual_date
        description: Date when the transaction should be recognized for accrual accounting purposes

      - name: cash_date
        description: Date when the cash transaction occurred or is expected to occur

      - name: description
        description: Detailed description of the transaction, standardized to 'No Description' when empty or NULL
        tests:
          - not_null  # Added because we're defaulting empty values
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 1
              max_value: 1000

      - name: gross_value
        description: Original transaction amount before any allocations or splits
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -10000000000  # Extended based on actual data
              max_value: 10000000000
              
      - name: net_value
        description: Final transaction amount after allocations or splits
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -10000000000  # Extended based on actual data
              max_value: 10000000000

      - name: currency_id
        description: Currency code for the transaction
        tests:
          - not_null

      - name: is_posted
        description: Indicates if the transaction has been posted to the general ledger
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: is_reconciled
        description: Indicates if the transaction has been reconciled
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: source_module
        description: System module that generated the transaction. Distribution as of analysis - GL (62M), AP (48.6M), Revenue (40.3M), AR (185K)
        tests:
          - not_null
          - accepted_values:
              values: ['GL', 'AP', 'Revenue', 'AR']

      - name: source_module_code
        description: Code representing the source module
        tests:
          - relationships:
              to: ref('stg_oda__source_module')  # Assuming this reference exists
              field: code

      - name: afe_id
        description: Reference to Authorization for Expenditure
        tests:
          - relationships:
              to: ref('stg_oda__afe_v2')
              field: id

      - name: create_date
        description: Timestamp when the record was created
        tests:
          - not_null
          

      - name: flow_published_at
        description: Timestamp when the record was published to the data flow
        tests:
          - not_null
          

  - name: stg_oda__account_sub_types
    description: |
      Staging model for Chart of Accounts Subtype classifications from Quorum OnDemand Accounting.
      This model contains the detailed subcategorization of accounts within each account type.
    columns:
      - name: account_subtype_id
        description: Unique identifier for the account subtype
        tests:
          - unique
          - not_null

      - name: account_type_id
        description: Foreign key to the parent account type
        tests:
          - not_null
          - relationships:
              to: ref('stg_oda__account_types')
              field: account_type_id

      - name: subtype_code
        description: Code used to identify the account subtype
        tests:
          - unique
          - not_null

      - name: subtype_name
        description: Short name of the account subtype
        tests:
          - not_null

      - name: subtype_full_name
        description: Full descriptive name of the account subtype
        tests:
          - not_null

      - name: normally_debit
        description: Flag indicating if accounts of this subtype normally have a debit balance
        tests:
          - not_null

      - name: record_insert_date
        description: Timestamp when the record was first inserted
        tests:
          - not_null

      - name: record_update_date
        description: Timestamp when the record was last updated

  - name: stg_oda__afe_v2
    description: |
      Staging model for Authorization for Expenditure (AFE) data from Quorum OnDemand Accounting v2.
      AFEs are used to request, track, and manage capital project budgets and expenditures.
    columns:
      - name: id
        description: Unique identifier for the AFE record
        tests:
          - unique
          - not_null

      - name: afe_v2_identity
        description: Unique identity number for the AFE in v2 system
        tests:
          - not_null

      - name: code
        description: Business identifier/number for the AFE
        tests:
          - not_null
          - unique

      - name: code_sort
        description: AFE code formatted for sorting purposes
        tests:
          - not_null

      - name: name
        description: Short name or title of the AFE
        tests:
          - not_null

      - name: full_name
        description: Complete name of the AFE
        tests:
          - not_null

      - name: afe_type_id
        description: Foreign key to AFE type classification
        tests:
          - not_null

      - name: afe_type_code
        description: Code representing the type of AFE
        tests:
          - not_null

      - name: application_type_id
        description: Foreign key to application type
        tests:
          - not_null

      - name: application_type_code
        description: Code indicating how the AFE is applied
        tests:
          - not_null

      - name: budget_usage_type_id
        description: Foreign key to budget usage type
        tests:
          - not_null

      - name: budget_usage_type_code
        description: Code indicating how the budget is used
        tests:
          - not_null

      - name: field_id
        description: Foreign key to field

      - name: operating_group_id
        description: Foreign key to operating group

      - name: default_company_code
        description: Code of the default company for this AFE
        tests:
          - not_null

      - name: create_date
        description: Timestamp when the record was created
        tests:
          - not_null

      - name: flow_published_at
        description: Timestamp when the record was published to the data flow
        tests:
          - not_null

  - name: stg_oda__account_v2
    description: |
      Staging model for Chart of Accounts data from Quorum OnDemand Accounting.
      This model standardizes column names and structures account information for downstream consumption.
    columns:
      - name: id
        description: Unique identifier for the account
        tests:
          - unique
          - not_null

      - name: code
        description: Account code used for identification
        tests:
          - not_null
          - unique

      - name: name
        description: Short name of the account
        tests:
          - not_null

      - name: full_name
        description: Full descriptive name of the account
        tests:
          - not_null

      - name: account_type_id
        description: Foreign key to account type
        tests:
          - not_null
          - relationships:
              to: ref('stg_oda__account_types')
              field: account_type_id

      - name: account_subtype_id
        description: Foreign key to account subtype
        tests:
          - relationships:
              to: ref('stg_oda__account_sub_types')
              field: account_subtype_id

      - name: active
        description: Flag indicating if the account is currently active
        tests:
          - not_null

      - name: normally_debit
        description: Flag indicating if the account normally has a debit balance
        tests:
          - not_null

      - name: account_sort
        description: Sorting value for the account
        tests:
          - not_null

      - name: key_sort
        description: Additional sorting key for the account

      - name: summarize_in_gl_reports
        description: Flag indicating if account should be summarized in GL reports
        tests:
          - not_null

      - name: summarize_in_jib_invoice
        description: Flag indicating if account should be summarized in JIB invoices
        tests:
          - not_null

      - name: bank_recon_performed
        description: Flag indicating if bank reconciliation is performed for this account
        tests:
          - not_null

      - name: create_date
        description: Timestamp when the record was created
        tests:
          - not_null

      - name: update_date
        description: Timestamp when the record was last updated

      - name: flow_published_at
        description: Timestamp when the record was published to the data flow
        tests:
          - not_null

