{{
    config(
        materialized='view',
        tags=['procount', 'staging', 'crescent']
    )
}}

with

source as (

    select * from {{ source('procount', 'COMPLETIONMONTHLYTB') }}

),

renamed as (

    select
        -- identifiers
        merrickid::number as merrick_id,
        theoreticalgasliquidsgpm::float as theoreticalgasliquidsgpm,
        loadfluidrecoveryflag::number as loadfluidrecovery_flag,
        ddaid::number as dda_id,
        trim(operatorwellid)::varchar as operatorwell_id,
        trim(engineeringid)::varchar as engineering_id,
        leaseid::number as lease_id,
        operatorentityid::number as operatorentity_id,
        areaid::number as area_id,
        groupid::number as group_id,
        outsideoperatedflag::number as outsideoperated_flag,
        trim(productionid)::varchar as production_id,
        divisionid::number as division_id,
        theoreticalprodgasliquids::float as theoreticalprodgasliquids,
        batteryid::number as battery_id,
        productionteamid::number as productionteam_id,
        drillingteamid::number as drillingteam_id,
        fieldgroupid::number as fieldgroup_id,
        platformid::number as platform_id,
        formationid::number as formation_id,
        daysidle::float as daysidle,
        accountingteamid::number as accountingteam_id,
        trim(accountingid)::varchar as accounting_id,
        totalhoursidle::float as totalhoursidle,
        gatheringsystemid::number as gathering_system_id,

        -- dates
        recorddate::timestamp_ntz as record_date,
        blogicdatestamp::timestamp_ntz as blogic_date_stamp,
        lastloaddate::timestamp_ntz as lastload_date,
        datetimestamp::timestamp_ntz as date_timestamp,
        enddate::timestamp_ntz as end_date,
        startdate::timestamp_ntz as start_date,
        trim(lastloadtime)::varchar as lastloadtime,
        userdatestamp::timestamp_ntz as user_date_stamp,
        totaldowntime::float as totaldowntime,
        operatoreffectivedate::timestamp_ntz as operatoreffective_date,
        allocationdatestamp::timestamp_ntz as allocation_date_stamp,

        -- well/completion attributes
        trim(completionnumber)::varchar as completion_number,
        trim(completionname)::varchar as completion_name,
        producingstatus::number as producingstatus,
        trim(wellnumber)::varchar as well_number,
        completiontype::number as completion_type,
        trim(wellname)::varchar as well_name,
        producingmethod::number as producingmethod,

        -- names and descriptions
        trim(deliverabilitycomment)::varchar as deliverabilitycomment,

        -- accounting/business entities
        trim(propertynumber)::varchar as property_number,
        operatorentityloc::number as operatorentityloc,

        -- volumes
        entconvinjgasvolmcf::float as entconvinjgas_vol_mcf,
        estco2vol::float as estco2vol,
        entconvinjothervol::float as entconvinjothervol,
        estgasvolmcf::float as estgas_vol_mcf,
        enteredoilvol::float as enteredoilvol,
        entconvinjgasvolmmbtu::float as entconvinjgas_vol_mmbtu,
        allocactgasvolmmbtu::float as allocactgas_vol_mmbtu,
        entconvothervol::float as entconvothervol,
        estinjwatervol::float as estinjwatervol,
        estinjgasvolmmbtu::float as estinjgas_vol_mmbtu,
        estinjco2vol::float as estinjco2vol,
        estinjgasvolmcf::float as estinjgas_vol_mcf,
        enteredinjgasvolmcf::float as enteredinjgas_vol_mcf,
        allocactrecoveryoilvol::float as allocactrecoveryoilvol,
        allocactnetgasvol::float as allocactnetgasvol,
        allocactothervol::float as allocactothervol,
        entconvoilvol::float as entconvoilvol,
        allocactgasvolmcf::float as allocactgas_vol_mcf,
        enteredinjothervol::float as enteredinjothervol,
        estwatervol::float as estwatervol,
        allocactinjco2vol::float as allocactinjco2vol,
        otherinjectiontype::number as otherinjection_type,
        estothervol::float as estothervol,
        allocactrecoverywatervol::float as allocactrecoverywatervol,
        enteredwatervol::float as enteredwatervol,
        entconvinjoilvol::float as entconvinjoilvol,
        entconvco2vol::float as entconvco2vol,
        enteredgasvolmcf::float as enteredgas_vol_mcf,
        allocactoilvol::float as allocactoilvol,
        enteredco2vol::float as enteredco2vol,
        enteredinjgasvolmmbtu::float as enteredinjgas_vol_mmbtu,
        entconvinjwatervol::float as entconvinjwatervol,
        allocactinjothervol::float as allocactinjothervol,
        allocactnglvol::float as allocactnglvol,
        allocactnetwatervol::float as allocactnetwatervol,
        enteredgasvolmmbtu::float as enteredgas_vol_mmbtu,
        enteredgasvolmcfleaseuse::float as enteredgasvolmcfleaseuse,
        estoilvol::float as estoilvol,
        allocactinjgasvolmmbtu::float as allocactinjgas_vol_mmbtu,
        estoilproduction::float as estoilproduction,
        enteredinjoilvol::float as enteredinjoilvol,
        enterednglvol::float as enterednglvol,
        estwaterproduction::float as estwaterproduction,
        estgasvolmmbtu::float as estgas_vol_mmbtu,
        estnglvol::float as estnglvol,
        enteredinjwatervol::float as enteredinjwatervol,
        entconvwatervol::float as entconvwatervol,
        allocactwatervol::float as allocactwatervol,
        waterproduction::float as waterproduction,
        estinjoilvol::float as estinjoilvol,
        oilproduction::float as oilproduction,
        allocactinjgasvolmcf::float as allocactinjgas_vol_mcf,
        enteredoilproduction::float as enteredoilproduction,
        enteredothervol::float as enteredothervol,
        allocactsalesgasvolmcf::float as allocactsalesgas_vol_mcf,
        enterednglproduction::float as enterednglproduction,
        allocactnetoilvol::float as allocactnetoilvol,
        entconvinjco2vol::float as entconvinjco2vol,
        estinjothervol::float as estinjothervol,
        allocactinjwatervol::float as allocactinjwatervol,
        entconvgasvolmmbtu::float as entconvgas_vol_mmbtu,
        entconvgasvolmcf::float as entconvgas_vol_mcf,
        enteredinjco2vol::float as enteredinjco2vol,
        allocactco2vol::float as allocactco2vol,
        allocactinjoilvol::float as allocactinjoilvol,
        enteredwaterproduction::float as enteredwaterproduction,
        allocactrecoverygasvol::float as allocactrecoverygasvol,
        leaseuseproduction::float as leaseuseproduction,

        -- pressures
        pressureclassification::number as pressureclassification,
        allocactpressurebase::float as allocactpressurebase,
        enteredpressurebase::float as enteredpressurebase,
        entconvpressurebase::float as entconvpressurebase,
        estpressurebase::float as estpressurebase,

        -- temperatures
        entconvtemperature::float as entconvtemperature,
        allocacttemperature::float as allocacttemperature,
        esttemperature::float as esttemperature,
        enteredtemperature::float as enteredtemperature,

        -- allocation factors
        entconvgravity::float as entconvgravity,
        enteredbtufactor::float as enteredbtufactor,
        allocationfactor::float as allocationfactor,
        equipallocfactor4::float as equipallocfactor4,
        allocactgravity::float as allocactgravity,
        equipallocfactor3::float as equipallocfactor3,
        equipallocfactor2::float as equipallocfactor2,
        estgravity::float as estgravity,
        enteredgravity::float as enteredgravity,
        allocationfactor8::float as allocationfactor8,
        entconvbtufactor::float as entconvbtufactor,
        allocationfactor7::float as allocationfactor7,
        allocationfactor6::float as allocationfactor6,
        allocationfactortype::number as allocationfactor_type,
        equipallocfactortype4::number as equipallocfactortype4,
        allocationfactor5::float as allocationfactor5,
        factorcomputationflag::number as factorcomputation_flag,
        theoreticalshrinkage::float as theoreticalshrinkage,
        allocationfactor4::float as allocationfactor4,
        equipallocfactortype3::number as equipallocfactortype3,
        allocationfactortype8::number as allocationfactortype8,
        equipallocfactortype2::number as equipallocfactortype2,
        allocationfactor3::float as allocationfactor3,
        allocationfactortype7::number as allocationfactortype7,
        allocationfactor2::float as allocationfactor2,
        allocationfactortype6::number as allocationfactortype6,
        estbtufactor::float as estbtufactor,
        allocationfactortype5::number as allocationfactortype5,
        allocationfactortype4::number as allocationfactortype4,
        equipallocfactor::float as equipallocfactor,
        allocationfactortype3::number as allocationfactortype3,
        equipallocfactortype::number as equipallocfactor_type,
        allocationfactortype2::number as allocationfactortype2,
        allocactbtufactor::float as allocactbtufactor,

        -- operational/equipment
        totalhoursflowed::float as totalhoursflowed,
        totalhoursrecovery::float as totalhoursrecovery,
        totalhoursinjected::float as totalhoursinjected,
        leaseusecompressor::float as leaseusecompressor,

        -- flags
        fixedvolumeflaggas::number as fixedvolumeflaggas,
        fixedvolumeflagwater::number as fixedvolumeflagwater,
        transmitflag::number as transmit_flag,
        datapopulationflag::number as datapopulation_flag,
        allocationactiveflag::number as allocationactive_flag,
        summationflag::number as summation_flag,
        entconvwetdryflag::number as entconvwetdry_flag,
        allocactwetdryflag::number as allocactwetdry_flag,
        calculationstatusflag::number as calculationstatus_flag,
        fixedvolumeflagoil::number as fixedvolumeflagoil,
        enteredasallocatedflag::number as enteredasallocated_flag,
        enteredwetdryflag::number as enteredwetdry_flag,
        backgroundtaskflag::number as backgroundtask_flag,
        estwetdryflag::number as estwetdry_flag,
        deliverabilitycalcflag::number as deliverabilitycalc_flag,

        -- audit/metadata
        userid::number as user_id,
        trim(rowuid)::varchar as rowu_id,
        trim(usertimestamp)::varchar as user_timestamp,
        _fivetran_deleted::boolean as _fivetran_deleted,
        _fivetran_synced::timestamp_tz as _fivetran_synced,

        -- other
        enteredendingoil::float as enteredendingoil,
        sustaineddeliverabilityoil::float as sustaineddeliverabilityoil,
        lasttransmission::number as lasttransmission,
        allocactsulfurmass::float as allocactsulfurmass,
        sustaineddeliverability::float as sustaineddeliverability,
        theoreticalprodgashighpres::float as theoreticalprodgashighpres,
        enteredgasliftmmbtu::float as enteredgasliftmmbtu,
        theoreticalprodgas::float as theoreticalprodgas,
        estendingwater::float as estendingwater,
        trim(allocationtimestamp)::varchar as allocation_timestamp,
        productcodegas::number as productcodegas,
        oilreserve::float as oilreserve,
        entconvgassalesvolmmbtu::float as entconvgassales_vol_mmbtu,
        gasendinginjinv::float as gasendinginjinv,
        enteredgasflashmcf::float as enteredgasflashmcf,
        cumulativewater::float as cumulativewater,
        enteredgasflaremcf::float as enteredgasflaremcf,
        estbeginningoil::float as estbeginningoil,
        gasbeginninginjinv::float as gasbeginninginjinv,
        daysinjected::float as daysinjected,
        cumulativeinjgas::float as cumulativeinjgas,
        reservesoil::float as reservesoil,
        theoreticalprodgaslift::float as theoreticalprodgaslift,
        otherendinginjinv::float as otherendinginjinv,
        estplantgasmcf::float as estplantgasmcf,
        beginningwater::float as beginningwater,
        lastentereddatachanged::timestamp_ntz as lastentereddatachanged,
        theoreticalprodoil::float as theoreticalprodoil,
        enteredbeginningoil::float as enteredbeginningoil,
        leaseuse::float as leaseuse,
        sustaineddeliverabilitygas::float as sustaineddeliverabilitygas,
        entconvgassalesvolmcf::float as entconvgassales_vol_mcf,
        estendingoil::float as estendingoil,
        endingoil::float as endingoil,
        entconvgasliftmmbtu::float as entconvgasliftmmbtu,
        reserveswater::float as reserveswater,
        cumulativegas::float as cumulativegas,
        trim(blogictimestamp)::varchar as blogic_timestamp,
        theoreticalprodwater::float as theoreticalprodwater,
        estbeginningwater::float as estbeginningwater,
        theoreticalinjoil::float as theoreticalinjoil,
        producttype::number as product_type,
        enteredretrogradevol::float as enteredretrogradevol,
        beginningoil::float as beginningoil,
        oilgasallocationratio::float as oilgasallocationratio,
        enteredgasliftmcf::float as enteredgasliftmcf,
        enteredendingwater::float as enteredendingwater,
        enteredbeginningwater::float as enteredbeginningwater,
        oiltargetprod::float as oiltargetprod,
        theoreticaloilwaterratio::float as theoreticaloilwaterratio,
        enteredendingngl::float as enteredendingngl,
        estsulfurmass::float as estsulfurmass,
        theoreticalprodco2::float as theoreticalprodco2,
        entconvplantgasmcf::float as entconvplantgasmcf,
        theoreticalprodgaslowpres::float as theoreticalprodgaslowpres,
        waterreserve::float as waterreserve,
        datasourcecode::number as datasource_code,
        reservesgas::float as reservesgas,
        oilruntickets::number as oilruntickets,
        endingwater::float as endingwater,
        waterbeginninginjinv::float as waterbeginninginjinv,
        productcodeoil::number as productcodeoil,
        theoreticalwatergpm::float as theoreticalwatergpm,
        productcodewater::number as productcodewater,
        oilbeginninginjinv::float as oilbeginninginjinv,
        watergasallocationratio::float as watergasallocationratio,
        tankcompdispoil::float as tankcompdispoil,
        theoreticalinjgasmcf::float as theoreticalinjgasmcf,
        theoreticalinjco2::float as theoreticalinjco2,
        enteredgassalesvolmmbtu::float as enteredgassales_vol_mmbtu,
        theoreticaloilgpm::float as theoreticaloilgpm,
        dispositioncode::number as disposition_code,
        allocactgasliftmcf::float as allocactgasliftmcf,
        cumulativeinjoil::float as cumulativeinjoil,
        waterruntickets::number as waterruntickets,
        otherbeginninginjinv::float as otherbeginninginjinv,
        productcode::number as product_code,
        reservecatagory::number as reservecatagory,
        gastargetprod::float as gastargetprod,
        allocactplantgasmmbtu::float as allocactplantgasmmbtu,
        gasoilratio::float as gasoilratio,
        gasreserve::float as gasreserve,
        enteredplantgasmcf::float as enteredplantgasmcf,
        enteredgasventedmcf::float as enteredgasventedmcf,
        enteredco2mass::float as enteredco2mass,
        enteredplantgasmmbtu::float as enteredplantgasmmbtu,
        oilendinginjinv::float as oilendinginjinv,
        allocactco2mass::float as allocactco2mass,
        trim(projectnumber)::varchar as project_number,
        enteredbeginningngl::float as enteredbeginningngl,
        cumulativeinjwater::float as cumulativeinjwater,
        cumulativeoil::float as cumulativeoil,
        entconvplantgasmmbtu::float as entconvplantgasmmbtu,
        enteredgassalesvolmcf::float as enteredgassales_vol_mcf,
        dayson::float as dayson,
        leaseusemarket::float as leaseusemarket,
        waterendinginjinv::float as waterendinginjinv,
        estco2mass::float as estco2mass,
        allocactplantgasmcf::float as allocactplantgasmcf,
        estplantgasmmbtu::float as estplantgasmmbtu,
        tankcompdispwater::float as tankcompdispwater,
        entconvgasliftmcf::float as entconvgasliftmcf,
        theoreticalinjwater::float as theoreticalinjwater

    from source

),

filtered as (

    select *
    from renamed
    where coalesce(_fivetran_deleted, false) = false
      and merrick_id is not null

),

enhanced as (

    select
        {{ dbt_utils.generate_surrogate_key(['merrick_id', 'record_date']) }} as completionmonthly_sk,
        *,
        current_timestamp() as _loaded_at

    from filtered

),

final as (

    select
        completionmonthly_sk,

        -- identifiers
        merrick_id,
        theoreticalgasliquidsgpm,
        loadfluidrecovery_flag,
        dda_id,
        operatorwell_id,
        engineering_id,
        lease_id,
        operatorentity_id,
        area_id,
        group_id,
        outsideoperated_flag,
        production_id,
        division_id,
        theoreticalprodgasliquids,
        battery_id,
        productionteam_id,
        drillingteam_id,
        fieldgroup_id,
        platform_id,
        formation_id,
        daysidle,
        accountingteam_id,
        accounting_id,
        totalhoursidle,
        gathering_system_id,

        -- dates
        record_date,
        blogic_date_stamp,
        lastload_date,
        date_timestamp,
        end_date,
        start_date,
        lastloadtime,
        user_date_stamp,
        totaldowntime,
        operatoreffective_date,
        allocation_date_stamp,

        -- well/completion attributes
        completion_number,
        completion_name,
        producingstatus,
        well_number,
        completion_type,
        well_name,
        producingmethod,

        -- names and descriptions
        deliverabilitycomment,

        -- accounting/business entities
        property_number,
        operatorentityloc,

        -- volumes
        entconvinjgas_vol_mcf,
        estco2vol,
        entconvinjothervol,
        estgas_vol_mcf,
        enteredoilvol,
        entconvinjgas_vol_mmbtu,
        allocactgas_vol_mmbtu,
        entconvothervol,
        estinjwatervol,
        estinjgas_vol_mmbtu,
        estinjco2vol,
        estinjgas_vol_mcf,
        enteredinjgas_vol_mcf,
        allocactrecoveryoilvol,
        allocactnetgasvol,
        allocactothervol,
        entconvoilvol,
        allocactgas_vol_mcf,
        enteredinjothervol,
        estwatervol,
        allocactinjco2vol,
        otherinjection_type,
        estothervol,
        allocactrecoverywatervol,
        enteredwatervol,
        entconvinjoilvol,
        entconvco2vol,
        enteredgas_vol_mcf,
        allocactoilvol,
        enteredco2vol,
        enteredinjgas_vol_mmbtu,
        entconvinjwatervol,
        allocactinjothervol,
        allocactnglvol,
        allocactnetwatervol,
        enteredgas_vol_mmbtu,
        enteredgasvolmcfleaseuse,
        estoilvol,
        allocactinjgas_vol_mmbtu,
        estoilproduction,
        enteredinjoilvol,
        enterednglvol,
        estwaterproduction,
        estgas_vol_mmbtu,
        estnglvol,
        enteredinjwatervol,
        entconvwatervol,
        allocactwatervol,
        waterproduction,
        estinjoilvol,
        oilproduction,
        allocactinjgas_vol_mcf,
        enteredoilproduction,
        enteredothervol,
        allocactsalesgas_vol_mcf,
        enterednglproduction,
        allocactnetoilvol,
        entconvinjco2vol,
        estinjothervol,
        allocactinjwatervol,
        entconvgas_vol_mmbtu,
        entconvgas_vol_mcf,
        enteredinjco2vol,
        allocactco2vol,
        allocactinjoilvol,
        enteredwaterproduction,
        allocactrecoverygasvol,
        leaseuseproduction,

        -- pressures
        pressureclassification,
        allocactpressurebase,
        enteredpressurebase,
        entconvpressurebase,
        estpressurebase,

        -- temperatures
        entconvtemperature,
        allocacttemperature,
        esttemperature,
        enteredtemperature,

        -- allocation factors
        entconvgravity,
        enteredbtufactor,
        allocationfactor,
        equipallocfactor4,
        allocactgravity,
        equipallocfactor3,
        equipallocfactor2,
        estgravity,
        enteredgravity,
        allocationfactor8,
        entconvbtufactor,
        allocationfactor7,
        allocationfactor6,
        allocationfactor_type,
        equipallocfactortype4,
        allocationfactor5,
        factorcomputation_flag,
        theoreticalshrinkage,
        allocationfactor4,
        equipallocfactortype3,
        allocationfactortype8,
        equipallocfactortype2,
        allocationfactor3,
        allocationfactortype7,
        allocationfactor2,
        allocationfactortype6,
        estbtufactor,
        allocationfactortype5,
        allocationfactortype4,
        equipallocfactor,
        allocationfactortype3,
        equipallocfactor_type,
        allocationfactortype2,
        allocactbtufactor,

        -- operational/equipment
        totalhoursflowed,
        totalhoursrecovery,
        totalhoursinjected,
        leaseusecompressor,

        -- flags
        fixedvolumeflaggas,
        fixedvolumeflagwater,
        transmit_flag,
        datapopulation_flag,
        allocationactive_flag,
        summation_flag,
        entconvwetdry_flag,
        allocactwetdry_flag,
        calculationstatus_flag,
        fixedvolumeflagoil,
        enteredasallocated_flag,
        enteredwetdry_flag,
        backgroundtask_flag,
        estwetdry_flag,
        deliverabilitycalc_flag,

        -- audit/metadata
        user_id,
        rowu_id,
        user_timestamp,
        _fivetran_deleted,
        _fivetran_synced,

        -- other
        enteredendingoil,
        sustaineddeliverabilityoil,
        lasttransmission,
        allocactsulfurmass,
        sustaineddeliverability,
        theoreticalprodgashighpres,
        enteredgasliftmmbtu,
        theoreticalprodgas,
        estendingwater,
        allocation_timestamp,
        productcodegas,
        oilreserve,
        entconvgassales_vol_mmbtu,
        gasendinginjinv,
        enteredgasflashmcf,
        cumulativewater,
        enteredgasflaremcf,
        estbeginningoil,
        gasbeginninginjinv,
        daysinjected,
        cumulativeinjgas,
        reservesoil,
        theoreticalprodgaslift,
        otherendinginjinv,
        estplantgasmcf,
        beginningwater,
        lastentereddatachanged,
        theoreticalprodoil,
        enteredbeginningoil,
        leaseuse,
        sustaineddeliverabilitygas,
        entconvgassales_vol_mcf,
        estendingoil,
        endingoil,
        entconvgasliftmmbtu,
        reserveswater,
        cumulativegas,
        blogic_timestamp,
        theoreticalprodwater,
        estbeginningwater,
        theoreticalinjoil,
        product_type,
        enteredretrogradevol,
        beginningoil,
        oilgasallocationratio,
        enteredgasliftmcf,
        enteredendingwater,
        enteredbeginningwater,
        oiltargetprod,
        theoreticaloilwaterratio,
        enteredendingngl,
        estsulfurmass,
        theoreticalprodco2,
        entconvplantgasmcf,
        theoreticalprodgaslowpres,
        waterreserve,
        datasource_code,
        reservesgas,
        oilruntickets,
        endingwater,
        waterbeginninginjinv,
        productcodeoil,
        theoreticalwatergpm,
        productcodewater,
        oilbeginninginjinv,
        watergasallocationratio,
        tankcompdispoil,
        theoreticalinjgasmcf,
        theoreticalinjco2,
        enteredgassales_vol_mmbtu,
        theoreticaloilgpm,
        disposition_code,
        allocactgasliftmcf,
        cumulativeinjoil,
        waterruntickets,
        otherbeginninginjinv,
        product_code,
        reservecatagory,
        gastargetprod,
        allocactplantgasmmbtu,
        gasoilratio,
        gasreserve,
        enteredplantgasmcf,
        enteredgasventedmcf,
        enteredco2mass,
        enteredplantgasmmbtu,
        oilendinginjinv,
        allocactco2mass,
        project_number,
        enteredbeginningngl,
        cumulativeinjwater,
        cumulativeoil,
        entconvplantgasmmbtu,
        enteredgassales_vol_mcf,
        dayson,
        leaseusemarket,
        waterendinginjinv,
        estco2mass,
        allocactplantgasmcf,
        estplantgasmmbtu,
        tankcompdispwater,
        entconvgasliftmcf,
        theoreticalinjwater,

        -- dbt metadata
        _loaded_at

    from enhanced

)

select * from final