{{
    config(
        materialized='view',
        tags=['procount', 'staging', 'crescent']
    )
}}

with

source as (

    select * from {{ source('procount', 'COMPLETIONDAILYTB') }}

),

renamed as (

    select
        -- identifiers
        merrickid::number as merrick_id,
        loadfluidrecoveryflag::number as loadfluidrecovery_flag,
        hoursidle::float as hoursidle,
        fluidlevel::float as fluidlevel,
        loadfluidcalcstatus::number as loadfluidcalcstatus,
        jointstofluid::float as jointstoflu_id,
        theoreticalprodgasliquids::float as theoreticalprodgasliquids,
        outsideoperatedflag::number as outsideoperated_flag,
        theoreticalgasliquidsgpm::float as theoreticalgasliquidsgpm,

        -- dates
        recorddate::timestamp_ntz as record_date,
        datetimestamp::timestamp_ntz as date_timestamp,
        lastentereddate::timestamp_ntz as lastentered_date,
        trim(readingtime)::varchar as readingtime,
        allocationdatestamp::timestamp_ntz as allocation_date_stamp,
        userdatestamp::timestamp_ntz as user_date_stamp,
        productiondate::timestamp_ntz as production_date,
        blogicdatestamp::timestamp_ntz as blogic_date_stamp,
        dailydowntime::float as dailydowntime,
        lastloaddate::timestamp_ntz as lastload_date,
        trim(lastloadtime)::varchar as lastloadtime,
        lastentereddatedays::number as lastentereddatedays,

        -- well/completion attributes
        producingmethod::number as producingmethod,
        bhpgaugedepth::float as bhpgaugedepth,
        producingstatus::number as producingstatus,

        -- volumes
        enteredothervol::float as enteredothervol,
        allocestnetwatervol::float as allocestnetwatervol,
        enteredoilvol::float as enteredoilvol,
        enteredgasvolmmbtu::float as enteredgas_vol_mmbtu,
        allocestinjgasvolmmbtu::float as alloc_est_inj_gas_vol_mmbtu,
        waterproduction::float as waterproduction,
        oilproduction::float as oilproduction,
        enteredinjco2vol::float as enteredinjco2vol,
        enteredgasvolmcf::float as enteredgas_vol_mcf,
        allocestrecoverygasvol::float as allocestrecoverygasvol,
        allocestinjwatervol::float as alloc_est_inj_water_vol,
        productiontarget::float as productiontarget,
        allocestinjco2vol::float as alloc_est_inj_co2_vol,
        gasinjection::float as gasinjection,
        enterednglvol::float as enterednglvol,
        allocestnetoilvol::float as allocestnetoilvol,
        enteredwaterproduction::float as enteredwaterproduction,
        enteredco2vol::float as enteredco2vol,
        allocestinjoilvol::float as alloc_est_inj_oil_vol,
        allocestinjgasvolmcf::float as alloc_est_inj_gas_vol_mcf,
        enterednglproduction::float as enterednglproduction,
        allocestinjothervol::float as alloc_est_inj_other_vol,
        allocestwatervol::float as alloc_est_water_vol,
        allocestrecoveryoilvol::float as allocestrecoveryoilvol,
        allocestnetgasvol::float as allocestnetgasvol,
        enteredwatervol::float as enteredwatervol,
        enteredinjgasvolmmbtu::float as enteredinjgas_vol_mmbtu,
        enteredoilproduction::float as enteredoilproduction,
        allocestrecoverywatervol::float as allocestrecoverywatervol,
        allocestgasvolmcf::float as alloc_est_gas_vol_mcf,
        enteredinjoilvol::float as enteredinjoilvol,
        oilinjection::float as oilinjection,
        enteredinjgasvolmcf::float as enteredinjgas_vol_mcf,
        allocestothervol::float as alloc_est_other_vol,
        allocestco2vol::float as alloc_est_co2_vol,
        injectionpressure::float as injectionpressure,
        allocestgasvolmmbtu::float as alloc_est_gas_vol_mmbtu,
        waterinjection::float as waterinjection,
        enteredinjwatervol::float as enteredinjwatervol,
        enteredgasvolmcfleaseuse::float as enteredgasvolmcfleaseuse,
        enteredinjothervol::float as enteredinjothervol,
        allocestoilvol::float as alloc_est_oil_vol,
        allocestnglvol::float as alloc_est_ngl_vol,

        -- rates
        proratedprodngl::float as proratedprodngl,
        ratewater::float as ratewater,
        rategasinj::float as rategasinj,
        proratedprodwater::float as proratedprodwater,
        proratedprodgas::float as proratedprodgas,
        rateoilinj::float as rateoilinj,
        proratedprodoil::float as proratedprodoil,
        rateoil::float as rateoil,
        ratewaterinj::float as ratewaterinj,
        rategas::float as rategas,

        -- pressures
        pressureclassification::number as pressureclassification,
        intercasingpressure::float as intercasingpressure,
        surfacecasingpressure::float as surfacecasingpressure,
        linercasingpressure::float as linercasingpressure,
        secondtubingpressure::float as secondtubingpressure,
        enteredpressurebase::float as enteredpressurebase,
        shutintubingpressure::float as shutintubingpressure,
        casingpressure::float as casingpressure,
        allocestpressurebase::float as alloc_est_pressure_base,
        othercasingpressure::float as othercasingpressure,
        tubingpressure::float as tubingpressure,

        -- temperatures
        enteredtemperature::float as enteredtemperature,
        allocesttemperature::float as alloc_est_temperature,
        bhtemperature::float as bhtemperature,
        tubingtemperature::float as tubingtemperature,

        -- allocation factors
        allocationfactortype6::number as allocationfactortype6,
        equipallocfactortype3::number as equipallocfactortype3,
        allocationfactor7::float as allocationfactor7,
        allocationfactortype7::number as allocationfactortype7,
        equipallocfactortype4::number as equipallocfactortype4,
        allocationfactor8::float as allocationfactor8,
        allocationfactortype::number as allocationfactor_type,
        equipallocfactor2::float as equipallocfactor2,
        allocationfactortype8::number as allocationfactortype8,
        enteredgravity::float as enteredgravity,
        equipallocfactor3::float as equipallocfactor3,
        enteredbtufactor::float as enteredbtufactor,
        equipallocfactor4::float as equipallocfactor4,
        allocationfactor2::float as allocationfactor2,
        factorcomputationflag::number as factorcomputation_flag,
        allocationfactor::float as allocationfactor,
        allocationfactortype2::number as allocationfactortype2,
        allocationfactor3::float as allocationfactor3,
        equipallocfactor::float as equipallocfactor,
        equipallocfactortype::number as equipallocfactor_type,
        allocationfactortype3::number as allocationfactortype3,
        allocestgravity::float as alloc_est_gravity,
        theoreticalshrinkage::float as theoreticalshrinkage,
        allocationfactor4::float as allocationfactor4,
        allocationfactortype4::number as allocationfactortype4,
        allocationfactor5::float as allocationfactor5,
        allocationfactortype5::number as allocationfactortype5,
        equipallocfactortype2::number as equipallocfactortype2,
        allocestbtufactor::float as alloc_est_btu_factor,
        allocationfactor6::float as allocationfactor6,

        -- operational/equipment
        chokesize::float as chokesize,
        pumpdepth::float as pumpdepth,
        hoursflowed::float as hoursflowed,
        trim(choke)::varchar as choke,
        hoursrecovery::float as hoursrecovery,
        hoursinjected::float as hoursinjected,

        -- flags
        fixedvolumeflagoil::number as fixedvolumeflagoil,
        backgroundtaskflag::number as backgroundtask_flag,
        allocestwetdryflag::number as alloc_est_wet_dry_flag,
        allocationactiveflag::number as allocationactive_flag,
        stilldownflag::number as stilldown_flag,
        trim(setupchangeflag)::varchar as setupchange_flag,
        fixedvolumeflaggas::number as fixedvolumeflaggas,
        completionflag::number as completion_flag,
        calculationstatusflag::number as calculationstatus_flag,
        datapopulationflag::number as datapopulation_flag,
        envcomplianceflag::number as envcompliance_flag,
        enteredwetdryflag::number as enteredwetdry_flag,
        enteredasallocatedflag::number as enteredasallocated_flag,
        fixedvolumeflagwater::number as fixedvolumeflagwater,
        transmitflag::number as transmit_flag,

        -- audit/metadata
        usernumber4::float as usernumber4,
        trim(usertimestamp)::varchar as user_timestamp,
        usernumber2::float as usernumber2,
        usernumber5::float as usernumber5,
        trim(userstringb)::varchar as userstringb,
        trim(userstringa)::varchar as userstringa,
        trim(rowuid)::varchar as rowu_id,
        usernumber3::float as usernumber3,
        userid::number as user_id,
        usernumber6::float as usernumber6,
        usernumber1::float as usernumber1,
        _fivetran_deleted::boolean as _fivetran_deleted,
        _fivetran_synced::timestamp_tz as _fivetran_synced,

        -- other
        gasendinginjinv::float as gasendinginjinv,
        lasttransmission::number as lasttransmission,
        enteredbeginningoil::float as enteredbeginningoil,
        enteredendingoil::float as enteredendingoil,
        allocationresulttype::number as allocationresult_type,
        enteredendingwater::float as enteredendingwater,
        gasbeginninginjinv::float as gasbeginninginjinv,
        productcode::number as product_code,
        dispositioncode::number as disposition_code,
        sustaineddeliverability::float as sustaineddeliverability,
        producttype::number as product_type,
        theoreticalprodco2::float as theoreticalprodco2,
        errornumber::number as error_number,
        enteredgasflaremcf::float as enteredgasflaremcf,
        allocestplantgasmmbtu::float as alloc_est_plant_gas_mmbtu,
        enteredplantgasmcf::float as enteredplantgasmcf,
        beginningoil::float as beginningoil,
        enteredretrogradevol::float as enteredretrogradevol,
        enteredbeginningngl::float as enteredbeginningngl,
        averagejointlength::float as averagejointlength,
        theoreticalinjco2::float as theoreticalinjco2,
        bhpshutin::float as bhpshutin,
        prorationmeter::number as prorationmeter,
        trim(allocationtimestamp)::varchar as allocation_timestamp,
        theoreticalinjgasmcf::float as theoreticalinjgasmcf,
        theoreticalprodgaslift::float as theoreticalprodgaslift,
        datasourcecode::number as datasource_code,
        theoreticaloilwaterratio::float as theoreticaloilwaterratio,
        waterbeginninginjinv::float as waterbeginninginjinv,
        gasoilratio::float as gasoilratio,
        theoreticalprodgas::float as theoreticalprodgas,
        theoreticaloilgpm::float as theoreticaloilgpm,
        theoreticalprodgashighpres::float as theoreticalprodgashighpres,
        theoreticalinjwater::float as theoreticalinjwater,
        enteredgasflashmcf::float as enteredgasflashmcf,
        allocestplantgasmcf::float as alloc_est_plant_gas_mcf,
        theoreticalprodoil::float as theoreticalprodoil,
        trim(blogictimestamp)::varchar as blogic_timestamp,
        bhpflowing::float as bhpflowing,
        sustaineddeliverabilityoil::float as sustaineddeliverabilityoil,
        theoreticalprodgaslowpres::float as theoreticalprodgaslowpres,
        theoreticalwatergpm::float as theoreticalwatergpm,
        enteredbeginningwater::float as enteredbeginningwater,
        enteredinjco2mass::float as enteredinjco2mass,
        enteredco2mass::float as enteredco2mass,
        allocestgasliftvol::float as allocestgasliftvol,
        otherendinginjinv::float as otherendinginjinv,
        theoreticalinjoil::float as theoreticalinjoil,
        oilendinginjinv::float as oilendinginjinv,
        waterendinginjinv::float as waterendinginjinv,
        enteredgasventedmcf::float as enteredgasventedmcf,
        endingoil::float as endingoil,
        enteredgassalesvolmcf::float as enteredgassales_vol_mcf,
        allocestsulfurmass::float as alloc_est_sulfur_mass,
        theoreticalprodwater::float as theoreticalprodwater,
        enteredgassalesvolmmbtu::float as enteredgassales_vol_mmbtu,
        sustaineddeliverabilitygas::float as sustaineddeliverabilitygas,
        enteredplantgasmmbtu::float as enteredplantgasmmbtu,
        oilbeginninginjinv::float as oilbeginninginjinv,
        endingwater::float as endingwater,
        trim(configurationmethod)::varchar as configurationmethod,
        enteredendingngl::float as enteredendingngl,
        otherbeginninginjinv::float as otherbeginninginjinv,
        beginningwater::float as beginningwater

    from source

),

filtered as (

    select *
    from renamed
    where coalesce(_fivetran_deleted, false) = false
      and merrick_id is not null

),

enhanced as (

    select
        {{ dbt_utils.generate_surrogate_key(['merrick_id', 'record_date']) }} as completiondaily_sk,
        *,
        current_timestamp() as _loaded_at

    from filtered

),

final as (

    select
        completiondaily_sk,

        -- identifiers
        merrick_id,
        loadfluidrecovery_flag,
        hoursidle,
        fluidlevel,
        loadfluidcalcstatus,
        jointstoflu_id,
        theoreticalprodgasliquids,
        outsideoperated_flag,
        theoreticalgasliquidsgpm,

        -- dates
        record_date,
        date_timestamp,
        lastentered_date,
        readingtime,
        allocation_date_stamp,
        user_date_stamp,
        production_date,
        blogic_date_stamp,
        dailydowntime,
        lastload_date,
        lastloadtime,
        lastentereddatedays,

        -- well/completion attributes
        producingmethod,
        bhpgaugedepth,
        producingstatus,

        -- volumes
        enteredothervol,
        allocestnetwatervol,
        enteredoilvol,
        enteredgas_vol_mmbtu,
        alloc_est_inj_gas_vol_mmbtu,
        waterproduction,
        oilproduction,
        enteredinjco2vol,
        enteredgas_vol_mcf,
        allocestrecoverygasvol,
        alloc_est_inj_water_vol,
        productiontarget,
        alloc_est_inj_co2_vol,
        gasinjection,
        enterednglvol,
        allocestnetoilvol,
        enteredwaterproduction,
        enteredco2vol,
        alloc_est_inj_oil_vol,
        alloc_est_inj_gas_vol_mcf,
        enterednglproduction,
        alloc_est_inj_other_vol,
        alloc_est_water_vol,
        allocestrecoveryoilvol,
        allocestnetgasvol,
        enteredwatervol,
        enteredinjgas_vol_mmbtu,
        enteredoilproduction,
        allocestrecoverywatervol,
        alloc_est_gas_vol_mcf,
        enteredinjoilvol,
        oilinjection,
        enteredinjgas_vol_mcf,
        alloc_est_other_vol,
        alloc_est_co2_vol,
        injectionpressure,
        alloc_est_gas_vol_mmbtu,
        waterinjection,
        enteredinjwatervol,
        enteredgasvolmcfleaseuse,
        enteredinjothervol,
        alloc_est_oil_vol,
        alloc_est_ngl_vol,

        -- rates
        proratedprodngl,
        ratewater,
        rategasinj,
        proratedprodwater,
        proratedprodgas,
        rateoilinj,
        proratedprodoil,
        rateoil,
        ratewaterinj,
        rategas,

        -- pressures
        pressureclassification,
        intercasingpressure,
        surfacecasingpressure,
        linercasingpressure,
        secondtubingpressure,
        enteredpressurebase,
        shutintubingpressure,
        casingpressure,
        alloc_est_pressure_base,
        othercasingpressure,
        tubingpressure,

        -- temperatures
        enteredtemperature,
        alloc_est_temperature,
        bhtemperature,
        tubingtemperature,

        -- allocation factors
        allocationfactortype6,
        equipallocfactortype3,
        allocationfactor7,
        allocationfactortype7,
        equipallocfactortype4,
        allocationfactor8,
        allocationfactor_type,
        equipallocfactor2,
        allocationfactortype8,
        enteredgravity,
        equipallocfactor3,
        enteredbtufactor,
        equipallocfactor4,
        allocationfactor2,
        factorcomputation_flag,
        allocationfactor,
        allocationfactortype2,
        allocationfactor3,
        equipallocfactor,
        equipallocfactor_type,
        allocationfactortype3,
        alloc_est_gravity,
        theoreticalshrinkage,
        allocationfactor4,
        allocationfactortype4,
        allocationfactor5,
        allocationfactortype5,
        equipallocfactortype2,
        alloc_est_btu_factor,
        allocationfactor6,

        -- operational/equipment
        chokesize,
        pumpdepth,
        hoursflowed,
        choke,
        hoursrecovery,
        hoursinjected,

        -- flags
        fixedvolumeflagoil,
        backgroundtask_flag,
        alloc_est_wet_dry_flag,
        allocationactive_flag,
        stilldown_flag,
        setupchange_flag,
        fixedvolumeflaggas,
        completion_flag,
        calculationstatus_flag,
        datapopulation_flag,
        envcompliance_flag,
        enteredwetdry_flag,
        enteredasallocated_flag,
        fixedvolumeflagwater,
        transmit_flag,

        -- audit/metadata
        usernumber4,
        user_timestamp,
        usernumber2,
        usernumber5,
        userstringb,
        userstringa,
        rowu_id,
        usernumber3,
        user_id,
        usernumber6,
        usernumber1,
        _fivetran_deleted,
        _fivetran_synced,

        -- other
        gasendinginjinv,
        lasttransmission,
        enteredbeginningoil,
        enteredendingoil,
        allocationresult_type,
        enteredendingwater,
        gasbeginninginjinv,
        product_code,
        disposition_code,
        sustaineddeliverability,
        product_type,
        theoreticalprodco2,
        error_number,
        enteredgasflaremcf,
        alloc_est_plant_gas_mmbtu,
        enteredplantgasmcf,
        beginningoil,
        enteredretrogradevol,
        enteredbeginningngl,
        averagejointlength,
        theoreticalinjco2,
        bhpshutin,
        prorationmeter,
        allocation_timestamp,
        theoreticalinjgasmcf,
        theoreticalprodgaslift,
        datasource_code,
        theoreticaloilwaterratio,
        waterbeginninginjinv,
        gasoilratio,
        theoreticalprodgas,
        theoreticaloilgpm,
        theoreticalprodgashighpres,
        theoreticalinjwater,
        enteredgasflashmcf,
        alloc_est_plant_gas_mcf,
        theoreticalprodoil,
        blogic_timestamp,
        bhpflowing,
        sustaineddeliverabilityoil,
        theoreticalprodgaslowpres,
        theoreticalwatergpm,
        enteredbeginningwater,
        enteredinjco2mass,
        enteredco2mass,
        allocestgasliftvol,
        otherendinginjinv,
        theoreticalinjoil,
        oilendinginjinv,
        waterendinginjinv,
        enteredgasventedmcf,
        endingoil,
        enteredgassales_vol_mcf,
        alloc_est_sulfur_mass,
        theoreticalprodwater,
        enteredgassales_vol_mmbtu,
        sustaineddeliverabilitygas,
        enteredplantgasmmbtu,
        oilbeginninginjinv,
        endingwater,
        configurationmethod,
        enteredendingngl,
        otherbeginninginjinv,
        beginningwater,

        -- dbt metadata
        _loaded_at

    from enhanced

)

select * from final