{{
    config(
        materialized='view',
        tags=['procount', 'staging', 'crescent']
    )
}}

with

source as (

    select * from {{ source('procount', 'METERDAILYTB') }}

),

renamed as (

    select
        -- identifiers
        merrickid::number as merrick_id,
        gatheringsystemid::number as gathering_system_id,
        commentid::number as comment_id,

        -- dates
        recorddate::timestamp_ntz as record_date,
        productiondate::timestamp_ntz as production_date,
        trim(lactopentime)::varchar as lactopentime,
        downtimeflag::number as downtime_flag,
        allocationdatestamp::timestamp_ntz as allocation_date_stamp,
        lactopendate::timestamp_ntz as lactopen_date,
        lastentereddatedays::number as lastentereddatedays,
        trim(lactclosetime)::varchar as lactclosetime,
        lastentereddate::timestamp_ntz as lastentered_date,
        lactclosedate::timestamp_ntz as lactclose_date,
        downtimehours::float as downtime_hours,
        trim(lastloadtime)::varchar as lastloadtime,
        userdatestamp::timestamp_ntz as user_date_stamp,
        blogicdatestamp::timestamp_ntz as blogic_date_stamp,
        datetimestamp::timestamp_ntz as date_timestamp,
        trim(readingtime)::varchar as readingtime,
        lastloaddate::timestamp_ntz as lastload_date,

        -- geography
        batteryprodoil::float as batteryprodoil,
        batteryprodgas::float as batteryprodgas,
        batteryprodwater::float as batteryprodwater,
        batteryprodngl::float as batteryprodngl,

        -- volumes
        allocoilvol::float as allocoilvol,
        allocothervol::float as allocothervol,
        estgasvolmmbtu::float as estgas_vol_mmbtu,
        netbarrels::float as netbarrels,
        allocgasvolmmbtu::float as allocgas_vol_mmbtu,
        convestgasvolmcf::float as convestgas_vol_mcf,
        estwatervol::float as estwatervol,
        estgasvolmcf::float as estgas_vol_mcf,
        estco2vol::float as estco2vol,
        injectionmeaspointflag::number as injectionmeaspoint_flag,
        fueluseoilvol::float as fueluseoilvol,
        grossbarrels::float as grossbarrels,
        convestco2vol::float as convestco2vol,
        convestothervol::float as convestothervol,
        estoilvol::float as estoilvol,
        fuelusegasvolmcf::float as fuelusegas_vol_mcf,
        allocco2vol::float as allocco2vol,
        allocwatervol::float as allocwatervol,
        estothervol::float as estothervol,
        convestgasvolmmbtu::float as convestgas_vol_mmbtu,
        fuelusegasvolmmbtu::float as fuelusegas_vol_mmbtu,
        estnglvol::float as estnglvol,
        allocgasvolmcf::float as allocgas_vol_mcf,
        convestoilvol::float as convestoilvol,
        fueluseothervol::float as fueluseothervol,
        convestwatervol::float as convestwatervol,

        -- rates
        rateco2::float as rateco2,
        ratecomputationflag::number as ratecomputation_flag,
        prorateusingfueluseflag::number as prorateusingfueluse_flag,
        rategas::float as rategas,
        ratewater::float as ratewater,
        rateoil::float as rateoil,

        -- pressures
        oilmetergaugepressure::float as oilmetergaugepressure,
        convestpressurebase::float as convestpressurebase,
        pressureclassification::number as pressureclassification,
        allocpressurebase::float as allocpressurebase,
        outputpressurepsia::float as outputpressurepsia,
        differentialpressure::float as differentialpressure,
        outputpressurepsig::float as outputpressurepsig,
        estpressurebase::float as estpressurebase,
        psiflag::number as psi_flag,
        absolutepressure::float as absolutepressure,
        staticpressurepsia::float as staticpressurepsia,
        linepressure::float as linepressure,
        staticpressurepsig::float as staticpressurepsig,

        -- temperatures
        closetemperature::float as closetemperature,
        gastemperature::float as gastemperature,
        temperaturerangelow::float as temperaturerangelow,
        opentemperature::float as opentemperature,
        convesttemperature::float as convesttemperature,
        temperaturerangehigh::float as temperaturerangehigh,
        esttemperature::float as esttemperature,
        alloctemperature::float as alloctemperature,
        observedtemperature::float as observedtemperature,

        -- allocation factors
        equipallocfactortype3::number as equipallocfactortype3,
        allocationfactortype4::number as allocationfactortype4,
        computecoefficientflag::number as computecoefficient_flag,
        shrinkagefactor::float as shrinkagefactor,
        convestgravity::float as convestgravity,
        factorcomputationflag::number as factorcomputation_flag,
        meteradjustmentfactor::float as meteradjustmentfactor,
        equipallocfactor3::float as equipallocfactor3,
        lactmeterfactor::float as lactmeterfactor,
        prorationfactorngl::float as prorationfactorngl,
        allocationfactor7::float as allocationfactor7,
        trim(allocationfactorcomment4)::varchar as allocationfactorcomment4,
        equipallocfactor::float as equipallocfactor,
        allocationfactortype5::number as allocationfactortype5,
        trim(equipallocfactorcomment)::varchar as equipallocfactorcomment,
        lactcompressibilityfactor::float as lactcompressibilityfactor,
        trim(allocationfactorcomment)::varchar as allocationfactorcomment,
        estbtufactor::float as estbtufactor,
        squarerootcoefficient::float as squarerootcoefficient,
        allocationfactortype7::number as allocationfactortype7,
        convestbtufactor::float as convestbtufactor,
        allocationfactor2::float as allocationfactor2,
        prorationfactoroil::float as prorationfactoroil,
        prorationfactorgas::float as prorationfactorgas,
        allocationfactortype::number as allocationfactor_type,
        linearcoefficient::float as linearcoefficient,
        allocationfactor6::float as allocationfactor6,
        estgravity::float as estgravity,
        gasequivalentfactor::float as gasequivalentfactor,
        equipallocfactortype::number as equipallocfactor_type,
        allocationfactor3::float as allocationfactor3,
        trim(equipallocfactorcomment2)::varchar as equipallocfactorcomment2,
        equipallocfactortype4::number as equipallocfactortype4,
        allocationfactortype2::number as allocationfactortype2,
        allocgravity::float as allocgravity,
        equipallocfactor4::float as equipallocfactor4,
        allocationfactor8::float as allocationfactor8,
        allocationfactor4::float as allocationfactor4,
        mfactor::float as mfactor,
        specificgravity::float as specificgravity,
        prorationfactorwater::float as prorationfactorwater,
        allocbtufactor::float as allocbtufactor,
        allocationfactortype6::number as allocationfactortype6,
        trim(allocationfactorcomment2)::varchar as allocationfactorcomment2,
        actualgravity::float as actualgravity,
        equipallocfactortype2::number as equipallocfactortype2,
        allocationfactortype3::number as allocationfactortype3,
        gasnominationbtufactor::float as gasnominationbtufactor,
        allocationfactor5::float as allocationfactor5,
        allocationfactor::float as allocationfactor,
        equipallocfactor2::float as equipallocfactor2,
        trim(allocationfactorcomment3)::varchar as allocationfactorcomment3,
        convertedgravity::float as convertedgravity,
        allocationfactortype8::number as allocationfactortype8,

        -- operational/equipment
        readinghours::float as readinghours,
        hoursflowed::float as hoursflowed,
        chokelength::float as chokelength,

        -- flags
        volumebasisflag::number as volumebasis_flag,
        fixedvolumeflagwater::number as fixedvolumeflagwater,
        odometerresetflag::number as odometerreset_flag,
        unitsflag::number as units_flag,
        metercalculationflag::number as metercalculation_flag,
        enteredvolumeflag::number as enteredvolume_flag,
        setupdatachangeflag::number as setupdatachange_flag,
        volumeautopopflag::number as volumeautopop_flag,
        calculationstatusflag::number as calculationstatus_flag,
        transmitflag::number as transmit_flag,
        estwetdryflag::number as estwetdry_flag,
        batteryprodcalcflag::number as batteryprodcalc_flag,
        fixedvolumeflagoil::number as fixedvolumeflagoil,
        allocwetdryflag::number as allocwetdry_flag,
        convestwetdryflag::number as convestwetdry_flag,
        fixedvolumeflaggas::number as fixedvolumeflaggas,
        backgroundtaskflag::number as backgroundtask_flag,
        loadtransferflag::number as loadtransfer_flag,
        physicalmeterflag::number as physicalmeter_flag,
        flangepipeflag::number as flangepipe_flag,

        -- audit/metadata
        userid::number as user_id,
        trim(rowuid)::varchar as rowu_id,
        trim(usertimestamp)::varchar as user_timestamp,
        _fivetran_deleted::boolean as _fivetran_deleted,
        _fivetran_synced::timestamp_tz as _fivetran_synced,

        -- other
        productcode::number as product_code,
        enteredvolume::float as enteredvolume,
        staticrange::float as staticrange,
        allocationorder::number as allocationorder,
        gasnominationmcf::float as gasnominationmcf,
        staticpercentreading::float as staticpercentreading,
        allocplantgasmmbtu::float as allocplantgasmmbtu,
        lactdensitycorrection::float as lactdensitycorrection,
        dispositioncode::number as disposition_code,
        allocwaterprod::float as allocwaterprod,
        producttype::number as product_type,
        estmass::float as estmass,
        estco2mass::float as estco2mass,
        differentialpercentreading::float as differentialpercentreading,
        closeodometer::float as closeodometer,
        metertype::number as meter_type,
        charttype::number as chart_type,
        gasnominationmmbtu::float as gasnominationmmbtu,
        allocoilprod::float as allocoilprod,
        allocco2mass::float as allocco2mass,
        allocationmethodupstream::number as allocationmethodupstream,
        orificeholdertype::number as orificeholder_type,
        pipetubediameter::float as pipetubediameter,
        trim(allocationtimestamp)::varchar as allocation_timestamp,
        chartcycle::number as chartcycle,
        allocatedvolumesource::number as allocatedvolumesource,
        estsulfurmass::float as estsulfurmass,
        differentialrootreading::float as differentialrootreading,
        trim(springsize)::varchar as springsize,
        allocationmethod::number as allocationmethod,
        datasourcecode::number as datasource_code,
        allocplantgasmcf::float as allocplantgasmcf,
        steamqualitypercent::float as steamqualitypercent,
        allocationbycomponent::number as allocationbycomponent,
        lasttransmission::number as lasttransmission,
        openodometer::float as openodometer,
        bsandw::float as bsandw,
        differentialrange::float as differentialrange,
        staticrootreading::float as staticrootreading,
        orificeplatediameter::float as orificeplatediameter,
        trim(blogictimestamp)::varchar as blogic_timestamp

    from source

),

filtered as (

    select *
    from renamed
    where coalesce(_fivetran_deleted, false) = false
      and merrick_id is not null

),

enhanced as (

    select
        {{ dbt_utils.generate_surrogate_key(['merrick_id', 'record_date']) }} as meterdaily_sk,
        *,
        current_timestamp() as _loaded_at

    from filtered

),

final as (

    select
        meterdaily_sk,

        -- identifiers
        merrick_id,
        gathering_system_id,
        comment_id,

        -- dates
        record_date,
        production_date,
        lactopentime,
        downtime_flag,
        allocation_date_stamp,
        lactopen_date,
        lastentereddatedays,
        lactclosetime,
        lastentered_date,
        lactclose_date,
        downtime_hours,
        lastloadtime,
        user_date_stamp,
        blogic_date_stamp,
        date_timestamp,
        readingtime,
        lastload_date,

        -- geography
        batteryprodoil,
        batteryprodgas,
        batteryprodwater,
        batteryprodngl,

        -- volumes
        allocoilvol,
        allocothervol,
        estgas_vol_mmbtu,
        netbarrels,
        allocgas_vol_mmbtu,
        convestgas_vol_mcf,
        estwatervol,
        estgas_vol_mcf,
        estco2vol,
        injectionmeaspoint_flag,
        fueluseoilvol,
        grossbarrels,
        convestco2vol,
        convestothervol,
        estoilvol,
        fuelusegas_vol_mcf,
        allocco2vol,
        allocwatervol,
        estothervol,
        convestgas_vol_mmbtu,
        fuelusegas_vol_mmbtu,
        estnglvol,
        allocgas_vol_mcf,
        convestoilvol,
        fueluseothervol,
        convestwatervol,

        -- rates
        rateco2,
        ratecomputation_flag,
        prorateusingfueluse_flag,
        rategas,
        ratewater,
        rateoil,

        -- pressures
        oilmetergaugepressure,
        convestpressurebase,
        pressureclassification,
        allocpressurebase,
        outputpressurepsia,
        differentialpressure,
        outputpressurepsig,
        estpressurebase,
        psi_flag,
        absolutepressure,
        staticpressurepsia,
        linepressure,
        staticpressurepsig,

        -- temperatures
        closetemperature,
        gastemperature,
        temperaturerangelow,
        opentemperature,
        convesttemperature,
        temperaturerangehigh,
        esttemperature,
        alloctemperature,
        observedtemperature,

        -- allocation factors
        equipallocfactortype3,
        allocationfactortype4,
        computecoefficient_flag,
        shrinkagefactor,
        convestgravity,
        factorcomputation_flag,
        meteradjustmentfactor,
        equipallocfactor3,
        lactmeterfactor,
        prorationfactorngl,
        allocationfactor7,
        allocationfactorcomment4,
        equipallocfactor,
        allocationfactortype5,
        equipallocfactorcomment,
        lactcompressibilityfactor,
        allocationfactorcomment,
        estbtufactor,
        squarerootcoefficient,
        allocationfactortype7,
        convestbtufactor,
        allocationfactor2,
        prorationfactoroil,
        prorationfactorgas,
        allocationfactor_type,
        linearcoefficient,
        allocationfactor6,
        estgravity,
        gasequivalentfactor,
        equipallocfactor_type,
        allocationfactor3,
        equipallocfactorcomment2,
        equipallocfactortype4,
        allocationfactortype2,
        allocgravity,
        equipallocfactor4,
        allocationfactor8,
        allocationfactor4,
        mfactor,
        specificgravity,
        prorationfactorwater,
        allocbtufactor,
        allocationfactortype6,
        allocationfactorcomment2,
        actualgravity,
        equipallocfactortype2,
        allocationfactortype3,
        gasnominationbtufactor,
        allocationfactor5,
        allocationfactor,
        equipallocfactor2,
        allocationfactorcomment3,
        convertedgravity,
        allocationfactortype8,

        -- operational/equipment
        readinghours,
        hoursflowed,
        chokelength,

        -- flags
        volumebasis_flag,
        fixedvolumeflagwater,
        odometerreset_flag,
        units_flag,
        metercalculation_flag,
        enteredvolume_flag,
        setupdatachange_flag,
        volumeautopop_flag,
        calculationstatus_flag,
        transmit_flag,
        estwetdry_flag,
        batteryprodcalc_flag,
        fixedvolumeflagoil,
        allocwetdry_flag,
        convestwetdry_flag,
        fixedvolumeflaggas,
        backgroundtask_flag,
        loadtransfer_flag,
        physicalmeter_flag,
        flangepipe_flag,

        -- audit/metadata
        user_id,
        rowu_id,
        user_timestamp,
        _fivetran_deleted,
        _fivetran_synced,

        -- other
        product_code,
        enteredvolume,
        staticrange,
        allocationorder,
        gasnominationmcf,
        staticpercentreading,
        allocplantgasmmbtu,
        lactdensitycorrection,
        disposition_code,
        allocwaterprod,
        product_type,
        estmass,
        estco2mass,
        differentialpercentreading,
        closeodometer,
        meter_type,
        chart_type,
        gasnominationmmbtu,
        allocoilprod,
        allocco2mass,
        allocationmethodupstream,
        orificeholder_type,
        pipetubediameter,
        allocation_timestamp,
        chartcycle,
        allocatedvolumesource,
        estsulfurmass,
        differentialrootreading,
        springsize,
        allocationmethod,
        datasource_code,
        allocplantgasmcf,
        steamqualitypercent,
        allocationbycomponent,
        lasttransmission,
        openodometer,
        bsandw,
        differentialrange,
        staticrootreading,
        orificeplatediameter,
        blogic_timestamp,

        -- dbt metadata
        _loaded_at

    from enhanced

)

select * from final