{{
    config(
        materialized='view',
        tags=['procount', 'staging', 'crescent']
    )
}}

with

source as (

    select * from {{ source('procount', 'METERMONTHLYTB') }}

),

renamed as (

    select
        -- identifiers
        merrickid::number as merrick_id,
        areaid::number as area_id,
        superpersonid::number as superperson_id,
        trim(purchasermeterid)::varchar as purchasermeter_id,
        integratorbeid::number as integratorbe_id,
        batteryid::number as battery_id,
        gathererbeid::number as gathererbe_id,
        trim(transporterid)::varchar as transporter_id,
        accountantpersonid::number as accountantperson_id,
        pumperpersonid::number as pumperperson_id,
        drillingteamid::number as drillingteam_id,
        trim(thirdpartymeterid)::varchar as thirdpartymeter_id,
        gatheringsystemid::number as gathering_system_id,
        trim(integratormeterid)::varchar as integratormeter_id,
        accountingteamid::number as accountingteam_id,
        divisionid::number as division_id,
        fieldgroupid::number as fieldgroup_id,
        checkmetermerrickid::number as checkmetermerrick_id,
        productionteamid::number as productionteam_id,
        transporterbeid::number as transporterbe_id,
        meteroperatorbeid::number as meteroperatorbe_id,
        foremanpersonid::number as foremanperson_id,
        purchaserbeid::number as purchaserbe_id,
        groupid::number as group_id,
        platformid::number as platform_id,
        trim(gathererid)::varchar as gatherer_id,

        -- dates
        recorddate::timestamp_ntz as record_date,
        lastloaddate::timestamp_ntz as lastload_date,
        trim(lastloadtime)::varchar as lastloadtime,
        lactopendate::timestamp_ntz as lactopen_date,
        userdatestamp::timestamp_ntz as user_date_stamp,
        trim(lactopentime)::varchar as lactopentime,
        totaldowntimehours::float as totaldowntimehours,
        allocationdatestamp::timestamp_ntz as allocation_date_stamp,
        lactclosedate::timestamp_ntz as lactclose_date,
        trim(lactclosetime)::varchar as lactclosetime,
        datetimestamp::timestamp_ntz as date_timestamp,
        blogicdatestamp::timestamp_ntz as blogic_date_stamp,
        enddate::timestamp_ntz as end_date,
        startdate::timestamp_ntz as start_date,

        -- names and descriptions
        trim(allocationcomment)::varchar as allocationcomment,

        -- accounting/business entities
        transporterbeloc::number as transporterbeloc,
        gathererbeloc::number as gathererbeloc,
        meteroperatorbeloc::number as meteroperatorbeloc,
        totalrunshaulerentered::number as totalrunshaulerentered,
        operator::number as operator,
        purchaserbeloc::number as purchaserbeloc,

        -- volumes
        actothervol::float as actothervol,
        convactoilvol::float as convactoilvol,
        estwatervol::float as estwatervol,
        allocothervol::float as allocothervol,
        convactothervol::float as convactothervol,
        allocoilvol::float as allocoilvol,
        fueluseothervol::float as fueluseothervol,
        fuelusegasvolmcf::float as fuelusegas_vol_mcf,
        grossbarrels::float as grossbarrels,
        estgasvolmmbtu::float as estgas_vol_mmbtu,
        fueluseoilvol::float as fueluseoilvol,
        actwatervol::float as actwatervol,
        actnglvol::float as actnglvol,
        convactwatervol::float as convactwatervol,
        estoilvol::float as estoilvol,
        dailyallocco2vol::float as dailyallocco2vol,
        actoilvol::float as actoilvol,
        convactco2vol::float as convactco2vol,
        allocwatervol::float as allocwatervol,
        allocgasvolmcf::float as allocgas_vol_mcf,
        estothervol::float as estothervol,
        convactgasvolmcf::float as convactgas_vol_mcf,
        netbarrels::float as netbarrels,
        convactgasvolmmbtu::float as convactgas_vol_mmbtu,
        actgasvolmmbtu::float as actgas_vol_mmbtu,
        estgasvolmcf::float as estgas_vol_mcf,
        fuelusegasvolmmbtu::float as fuelusegas_vol_mmbtu,
        estco2vol::float as estco2vol,
        dailyallocoilvol::float as dailyallocoilvol,
        allocco2vol::float as allocco2vol,
        allocgasvolmmbtu::float as allocgas_vol_mmbtu,
        actgasvolmcf::float as actgas_vol_mcf,
        dailyallocwatervol::float as dailyallocwatervol,
        dailyallocgasvolmcf::float as dailyallocgas_vol_mcf,
        dailyallocothervol::float as dailyallocothervol,
        actco2vol::float as actco2vol,
        injectionmeaspointflag::number as injectionmeaspoint_flag,
        dailyallocgasvolmmbtu::float as dailyallocgas_vol_mmbtu,

        -- rates
        prorateusingfueluseflag::number as prorateusingfueluse_flag,

        -- pressures
        actpressurebase::float as actpressurebase,
        pressureclassification::number as pressureclassification,
        convactpressurebase::float as convactpressurebase,
        dailyallocpressurebase::float as dailyallocpressurebase,
        allocpressurebase::float as allocpressurebase,
        estpressurebase::float as estpressurebase,

        -- temperatures
        acttemperature::float as acttemperature,
        convacttemperature::float as convacttemperature,
        alloctemperature::float as alloctemperature,
        dailyalloctemperature::float as dailyalloctemperature,
        esttemperature::float as esttemperature,
        opentemperature::float as opentemperature,
        observedtemperature::float as observedtemperature,
        closetemperature::float as closetemperature,

        -- allocation factors
        convertedgravity::float as convertedgravity,
        equipallocfactorautoflag::number as equipallocfactorauto_flag,
        meteradjustmentfactor::float as meteradjustmentfactor,
        equipallocfactortype3::number as equipallocfactortype3,
        dailyallocbtufactor::float as dailyallocbtufactor,
        estgravity::float as estgravity,
        allocationfactortype::number as allocationfactor_type,
        linearcoefficient::float as linearcoefficient,
        actgravity::float as actgravity,
        errorcorrectionfactordaily::float as errorcorrectionfactordaily,
        trim(allocationfactorcomment)::varchar as allocationfactorcomment,
        trim(equipallocfactorcomment2)::varchar as equipallocfactorcomment2,
        equipallocfactor4::float as equipallocfactor4,
        allocationfactortype8::number as allocationfactortype8,
        allocationfactortype4::number as allocationfactortype4,
        trim(allocationfactorcomment3)::varchar as allocationfactorcomment3,
        gasequivalentfactor::float as gasequivalentfactor,
        factorcomputationflag::number as factorcomputation_flag,
        trim(equipallocfactorcomment)::varchar as equipallocfactorcomment,
        allocationfactortype2::number as allocationfactortype2,
        allocationfactor8::float as allocationfactor8,
        equipallocfactor3::float as equipallocfactor3,
        dailyallocgravity::float as dailyallocgravity,
        allocationfactor4::float as allocationfactor4,
        allocationfactortype7::number as allocationfactortype7,
        allocationfactor2::float as allocationfactor2,
        convactgravity::float as convactgravity,
        allocationfactor7::float as allocationfactor7,
        equipallocfactortype2::number as equipallocfactortype2,
        allocationfactortype6::number as allocationfactortype6,
        shrinkagefactor::float as shrinkagefactor,
        allocationfactor::float as allocationfactor,
        allocbtufactor::float as allocbtufactor,
        errorcorrectionfactor::float as errorcorrectionfactor,
        lactcompressibilityfactor::float as lactcompressibilityfactor,
        allocationfactorautoflag::number as allocationfactorauto_flag,
        lactmeterfactor::float as lactmeterfactor,
        convactbtufactor::float as convactbtufactor,
        allocationfactor6::float as allocationfactor6,
        equipallocfactortype::number as equipallocfactor_type,
        allocationfactortype5::number as allocationfactortype5,
        trim(allocationfactorcomment4)::varchar as allocationfactorcomment4,
        estbtufactor::float as estbtufactor,
        prorationfactor::float as prorationfactor,
        allocationfactortype3::number as allocationfactortype3,
        trim(allocationfactorcomment2)::varchar as allocationfactorcomment2,
        allocationfactor5::float as allocationfactor5,
        equipallocfactortype4::number as equipallocfactortype4,
        actualgravity::float as actualgravity,
        equipallocfactor2::float as equipallocfactor2,
        allocationfactor3::float as allocationfactor3,
        equipallocfactor::float as equipallocfactor,
        allocgravity::float as allocgravity,
        actbtufactor::float as actbtufactor,

        -- operational/equipment
        totalrunspumperentered::number as totalrunspumperentered,
        totalhoursflowed::float as totalhoursflowed,

        -- flags
        actwetdryflag::number as actwetdry_flag,
        convactwetdryflag::number as convactwetdry_flag,
        transmitflag::number as transmit_flag,
        activeflag::number as active_flag,
        fixedvolumeflaggas::number as fixedvolumeflaggas,
        summationflag::number as summation_flag,
        calculationstatusflag::number as calculationstatus_flag,
        monthlydatasourceflag::number as monthlydatasource_flag,
        backgroundtaskflag::number as backgroundtask_flag,
        volumebasisflag::number as volumebasis_flag,
        dailyallocwetdryflag::number as dailyallocwetdry_flag,
        fixedvolumeflagwater::number as fixedvolumeflagwater,
        unitsflag::number as units_flag,
        odometerresetflag::number as odometerreset_flag,
        actualvolumeautopopflag::number as actualvolumeautopop_flag,
        loadtransferflag::number as loadtransfer_flag,
        physicalmeterflag::number as physicalmeter_flag,
        estwetdryflag::number as estwetdry_flag,
        allocwetdryflag::number as allocwetdry_flag,
        fixedvolumeflagoil::number as fixedvolumeflagoil,
        equipmentfuelusageflag::number as equipmentfuelusage_flag,

        -- audit/metadata
        trim(rowuid)::varchar as rowu_id,
        userid::number as user_id,
        trim(usertimestamp)::varchar as user_timestamp,
        _fivetran_deleted::boolean as _fivetran_deleted,
        _fivetran_synced::timestamp_tz as _fivetran_synced,

        -- other
        actmass::float as actmass,
        allocationmethodupstream::number as allocationmethodupstream,
        dayson::float as dayson,
        trim(springsize)::varchar as springsize,
        trim(allocationtimestamp)::varchar as allocation_timestamp,
        measurementpointrole::number as measurementpointrole,
        allocationbycomponent::number as allocationbycomponent,
        allocwaterprod::float as allocwaterprod,
        metertype::number as meter_type,
        productcode::number as product_code,
        estco2mass::float as estco2mass,
        btuvalue::float as btuvalue,
        trim(blogictimestamp)::varchar as blogic_timestamp,
        allocatedvolumesource::number as allocatedvolumesource,
        actsulfurmass::float as actsulfurmass,
        lasttransmission::number as lasttransmission,
        allocplantgasmcf::float as allocplantgasmcf,
        bsandw::float as bsandw,
        allocco2mass::float as allocco2mass,
        integratorbeloc::number as integratorbeloc,
        allocationmethod::number as allocationmethod,
        producttype::number as product_type,
        actco2mass::float as actco2mass,
        platesize::float as platesize,
        openodometer::float as openodometer,
        dailyallocplantgasmcf::float as dailyallocplantgasmcf,
        oilpipelinevol::float as oilpipelinevol,
        dispositioncode::number as disposition_code,
        datasourcecode::number as datasource_code,
        closeodometer::float as closeodometer,
        lactdensitycorrection::float as lactdensitycorrection,
        dailyallocplantgasmmbtu::float as dailyallocplantgasmmbtu,
        allocplantgasmmbtu::float as allocplantgasmmbtu,
        allocoilprod::float as allocoilprod,
        allocationorder::number as allocationorder

    from source

),

filtered as (

    select *
    from renamed
    where coalesce(_fivetran_deleted, false) = false
      and merrick_id is not null

),

enhanced as (

    select
        {{ dbt_utils.generate_surrogate_key(['merrick_id', 'record_date']) }} as metermonthly_sk,
        *,
        current_timestamp() as _loaded_at

    from filtered

),

final as (

    select
        metermonthly_sk,

        -- identifiers
        merrick_id,
        area_id,
        superperson_id,
        purchasermeter_id,
        integratorbe_id,
        battery_id,
        gathererbe_id,
        transporter_id,
        accountantperson_id,
        pumperperson_id,
        drillingteam_id,
        thirdpartymeter_id,
        gathering_system_id,
        integratormeter_id,
        accountingteam_id,
        division_id,
        fieldgroup_id,
        checkmetermerrick_id,
        productionteam_id,
        transporterbe_id,
        meteroperatorbe_id,
        foremanperson_id,
        purchaserbe_id,
        group_id,
        platform_id,
        gatherer_id,

        -- dates
        record_date,
        lastload_date,
        lastloadtime,
        lactopen_date,
        user_date_stamp,
        lactopentime,
        totaldowntimehours,
        allocation_date_stamp,
        lactclose_date,
        lactclosetime,
        date_timestamp,
        blogic_date_stamp,
        end_date,
        start_date,

        -- names and descriptions
        allocationcomment,

        -- accounting/business entities
        transporterbeloc,
        gathererbeloc,
        meteroperatorbeloc,
        totalrunshaulerentered,
        operator,
        purchaserbeloc,

        -- volumes
        actothervol,
        convactoilvol,
        estwatervol,
        allocothervol,
        convactothervol,
        allocoilvol,
        fueluseothervol,
        fuelusegas_vol_mcf,
        grossbarrels,
        estgas_vol_mmbtu,
        fueluseoilvol,
        actwatervol,
        actnglvol,
        convactwatervol,
        estoilvol,
        dailyallocco2vol,
        actoilvol,
        convactco2vol,
        allocwatervol,
        allocgas_vol_mcf,
        estothervol,
        convactgas_vol_mcf,
        netbarrels,
        convactgas_vol_mmbtu,
        actgas_vol_mmbtu,
        estgas_vol_mcf,
        fuelusegas_vol_mmbtu,
        estco2vol,
        dailyallocoilvol,
        allocco2vol,
        allocgas_vol_mmbtu,
        actgas_vol_mcf,
        dailyallocwatervol,
        dailyallocgas_vol_mcf,
        dailyallocothervol,
        actco2vol,
        injectionmeaspoint_flag,
        dailyallocgas_vol_mmbtu,

        -- rates
        prorateusingfueluse_flag,

        -- pressures
        actpressurebase,
        pressureclassification,
        convactpressurebase,
        dailyallocpressurebase,
        allocpressurebase,
        estpressurebase,

        -- temperatures
        acttemperature,
        convacttemperature,
        alloctemperature,
        dailyalloctemperature,
        esttemperature,
        opentemperature,
        observedtemperature,
        closetemperature,

        -- allocation factors
        convertedgravity,
        equipallocfactorauto_flag,
        meteradjustmentfactor,
        equipallocfactortype3,
        dailyallocbtufactor,
        estgravity,
        allocationfactor_type,
        linearcoefficient,
        actgravity,
        errorcorrectionfactordaily,
        allocationfactorcomment,
        equipallocfactorcomment2,
        equipallocfactor4,
        allocationfactortype8,
        allocationfactortype4,
        allocationfactorcomment3,
        gasequivalentfactor,
        factorcomputation_flag,
        equipallocfactorcomment,
        allocationfactortype2,
        allocationfactor8,
        equipallocfactor3,
        dailyallocgravity,
        allocationfactor4,
        allocationfactortype7,
        allocationfactor2,
        convactgravity,
        allocationfactor7,
        equipallocfactortype2,
        allocationfactortype6,
        shrinkagefactor,
        allocationfactor,
        allocbtufactor,
        errorcorrectionfactor,
        lactcompressibilityfactor,
        allocationfactorauto_flag,
        lactmeterfactor,
        convactbtufactor,
        allocationfactor6,
        equipallocfactor_type,
        allocationfactortype5,
        allocationfactorcomment4,
        estbtufactor,
        prorationfactor,
        allocationfactortype3,
        allocationfactorcomment2,
        allocationfactor5,
        equipallocfactortype4,
        actualgravity,
        equipallocfactor2,
        allocationfactor3,
        equipallocfactor,
        allocgravity,
        actbtufactor,

        -- operational/equipment
        totalrunspumperentered,
        totalhoursflowed,

        -- flags
        actwetdry_flag,
        convactwetdry_flag,
        transmit_flag,
        active_flag,
        fixedvolumeflaggas,
        summation_flag,
        calculationstatus_flag,
        monthlydatasource_flag,
        backgroundtask_flag,
        volumebasis_flag,
        dailyallocwetdry_flag,
        fixedvolumeflagwater,
        units_flag,
        odometerreset_flag,
        actualvolumeautopop_flag,
        loadtransfer_flag,
        physicalmeter_flag,
        estwetdry_flag,
        allocwetdry_flag,
        fixedvolumeflagoil,
        equipmentfuelusage_flag,

        -- audit/metadata
        rowu_id,
        user_id,
        user_timestamp,
        _fivetran_deleted,
        _fivetran_synced,

        -- other
        actmass,
        allocationmethodupstream,
        dayson,
        springsize,
        allocation_timestamp,
        measurementpointrole,
        allocationbycomponent,
        allocwaterprod,
        meter_type,
        product_code,
        estco2mass,
        btuvalue,
        blogic_timestamp,
        allocatedvolumesource,
        actsulfurmass,
        lasttransmission,
        allocplantgasmcf,
        bsandw,
        allocco2mass,
        integratorbeloc,
        allocationmethod,
        product_type,
        actco2mass,
        platesize,
        openodometer,
        dailyallocplantgasmcf,
        oilpipelinevol,
        disposition_code,
        datasource_code,
        closeodometer,
        lactdensitycorrection,
        dailyallocplantgasmmbtu,
        allocplantgasmmbtu,
        allocoilprod,
        allocationorder,

        -- dbt metadata
        _loaded_at

    from enhanced

)

select * from final