{{
    config(
        materialized='view',
        tags=['procount', 'staging', 'crescent']
    )
}}

with

source as (

    select * from {{ source('procount', 'COMPLETIONTB') }}

),

renamed as (

    select
        -- identifiers
        merrickid::number as merrick_id,
        allocationgroupid::number as allocationgroup_id,
        regsreservoirid::number as regsreservoir_id,
        countryid::number as country_id,
        locationmerrickid::number as location_merrick_id,
        operatorentityid::number as operatorentity_id,
        countyid::number as county_id,
        outsideoperatedflag::number as outsideoperated_flag,
        formationid::number as formation_id,
        reservoirid::number as reservoir_id,
        trim(statefilingid)::varchar as statefiling_id,
        parametertemplateid::number as parametertemplate_id,
        divisionid::number as division_id,
        trim(productionid)::varchar as production_id,
        accountingteamid::number as accountingteam_id,
        facilityid::number as facility_id,
        trim(rioprodid)::varchar as rioprod_id,
        regulatoryfieldid::number as regulatoryfield_id,
        batteryid::number as battery_id,
        loadfluidsourceid::number as loadfluidsource_id,
        pumperpersonid::number as pumperperson_id,
        validationdaysback::number as validationdaysback,
        plantid::number as plant_id,
        groupid::number as group_id,
        completionfluidtype::number as completionfluid_type,
        trim(accountingid)::varchar as accounting_id,
        trim(ihsid)::varchar as ihs_id,
        stateid::number as state_id,
        gatheringsystemid::number as gathering_system_id,
        trim(engineeringid)::varchar as engineering_id,
        fieldgroupid::number as fieldgroup_id,
        areaid::number as area_id,
        trim(rioid)::varchar as rio_id,
        foremanpersonid::number as foremanperson_id,
        loadfluidsourcetype::number as loadfluidsource_type,
        propertywellid::number as propertywell_id,
        reserveauditorid::number as reserveauditor_id,
        computeloadfluid::number as computeloadflu_id,
        ddaid::number as dda_id,
        productionteamid::number as productionteam_id,
        gasanalysissourceid::number as gasanalysissource_id,
        leaseid::number as lease_id,
        unitid::number as unit_id,
        trim(wellviewid)::varchar as wellview_id,
        injectiongatheringsystemid::number as injectiongatheringsystem_id,
        trim(uwidisplay)::varchar as uwidisplay,
        trim(operatorwellid)::varchar as operatorwell_id,
        engineerpersonid::number as engineerperson_id,
        accountantpersonid::number as accountantperson_id,
        trim(scadaid)::varchar as scada_id,
        platformid::number as platform_id,
        superpersonid::number as superperson_id,
        drillingteamid::number as drillingteam_id,
        routeid::number as route_id,
        trim(petroregsid)::varchar as petroregs_id,

        -- dates
        dateofinitialproductionoil::timestamp_ntz as dateofinitialproductionoil,
        datewellsold::timestamp_ntz as datewellsold,
        startactivedate::timestamp_ntz as startactive_date,
        cleanupdatestamp::timestamp_ntz as cleanupdatestamp,
        datetimestamp::timestamp_ntz as date_timestamp,
        endactivedate::timestamp_ntz as endactive_date,
        allocautostartdate::timestamp_ntz as allocautostart_date,
        datecompleted::timestamp_ntz as datecompleted,
        recordcreationdate::timestamp_ntz as recordcreation_date,
        lastproductiondate::timestamp_ntz as lastproduction_date,
        dateofinitialproductiongas::timestamp_ntz as dateofinitialproductiongas,
        blogicdatestamp::timestamp_ntz as blogic_date_stamp,
        lastloaddate::timestamp_ntz as lastload_date,
        datewellacquired::timestamp_ntz as datewellacquired,
        laststatuschangeddate::timestamp_ntz as laststatuschanged_date,
        trim(lastloadtime)::varchar as lastloadtime,
        trim(cleanuptimestamp)::varchar as cleanuptimestamp,
        dataeditstartdate::timestamp_ntz as dataeditstart_date,
        allocationtypestartdate::timestamp_ntz as allocationtypestart_date,
        lasttestdate::timestamp_ntz as lasttest_date,
        dateshutin::timestamp_ntz as dateshutin,
        rigreleasedate::timestamp_ntz as rigrelease_date,
        userdatestamp::timestamp_ntz as user_date_stamp,
        dateabandoned::timestamp_ntz as dateabandoned,

        -- well/completion attributes
        producingstatus::number as producingstatus,
        trim(completionnumber)::varchar as completion_number,
        trim(mmswellname)::varchar as mmswell_name,
        trim(wellname)::varchar as well_name,
        trim(uwisurface)::varchar as uwisurface,
        completionstatus::number as completionstatus,
        trim(mmsapiwellnumber)::varchar as mmsapiwell_number,
        thirdtodepth::float as thirdtodepth,
        lastproducingmethod::number as lastproducingmethod,
        trim(regulatorycompletion)::varchar as regulatorycompletion,
        thirdfromdepth::float as thirdfromdepth,
        lastproducingstatus::number as lastproducingstatus,
        completionflowdirection::number as completionflowdirection,
        uwitype::number as uwi_type,
        trim(uwisurfacedisplay)::varchar as uwisurfacedisplay,
        trim(wellpluscompletionname)::varchar as wellpluscompletion_name,
        trim(uwi)::varchar as uwi,
        todepth::float as todepth,
        trim(completionname)::varchar as completion_name,
        trim(mmsproducinginterval)::varchar as mmsproducinginterval,
        secondtodepth::float as secondtodepth,
        completiontype::number as completion_type,
        fromdepth::float as fromdepth,
        trim(wellnumber)::varchar as well_number,
        trim(wellborediagramreference)::varchar as wellborediagramreference,
        packerdepth::float as packerdepth,
        trim(apicompletionnumber)::varchar as apicompletion_number,
        producingmethod::number as producingmethod,
        secondfromdepth::float as secondfromdepth,
        trim(apiwellnumber)::varchar as apiwell_number,
        waterdepth::float as waterdepth,

        -- names and descriptions
        trim(userstringflabel)::varchar as userstringflabel,
        trim(accountingpropertyname)::varchar as accountingproperty_name,
        trim(usernumber6label)::varchar as usernumber6label,
        trim(jibpropertyname)::varchar as jibproperty_name,
        trim(userstringalabel)::varchar as userstringalabel,
        trim(userdailynumber1label)::varchar as userdailynumber1label,
        trim(userdailynumber2label)::varchar as userdailynumber2label,
        trim(userstringblabel)::varchar as userstringblabel,
        trim(userdailynumber3label)::varchar as userdailynumber3label,
        trim(userdailynumber4label)::varchar as userdailynumber4label,
        trim(userdailystringalabel)::varchar as userdailystringalabel,
        trim(userstringclabel)::varchar as userstringclabel,
        trim(setupcomments)::varchar as setupcomments,
        trim(usernumber1label)::varchar as usernumber1label,
        trim(revenuepropertyname)::varchar as revenueproperty_name,
        trim(accountingshortname)::varchar as accountingshort_name,
        trim(commingleddescription)::varchar as commingleddescription,
        trim(usernumber2label)::varchar as usernumber2label,
        trim(userdailynumber5label)::varchar as userdailynumber5label,
        trim(userdailystringblabel)::varchar as userdailystringblabel,
        trim(userdailynumber6label)::varchar as userdailynumber6label,
        trim(allocationdailycomment)::varchar as allocationdailycomment,
        trim(usernumber3label)::varchar as usernumber3label,
        trim(allocationmonthlycomment)::varchar as allocationmonthlycomment,
        trim(userstringdlabel)::varchar as userstringdlabel,
        trim(usernumber4label)::varchar as usernumber4label,
        trim(landpropertyname)::varchar as landproperty_name,
        trim(userstringelabel)::varchar as userstringelabel,
        trim(usernumber5label)::varchar as usernumber5label,

        -- geography
        trim(latitude)::varchar as latitude,
        trim(stateleasename)::varchar as statelease_name,
        trim(stateproducingzone)::varchar as stateproducingzone,
        trim(stateapiwellnumber)::varchar as stateapiwell_number,
        trim(longitude)::varchar as longitude,
        trim(statepropertycode)::varchar as stateproperty_code,
        trim(statedistrictnumber)::varchar as statedistrict_number,
        trim(statewellnumber)::varchar as statewell_number,

        -- accounting/business entities
        operatorentityloc::number as operatorentityloc,
        trim(propertynumber)::varchar as property_number,

        -- volumes
        sigasvolconversion::float as sigasvolconversion,
        reportproductionflag::number as reportproduction_flag,
        gasproductionfactorflag::number as gasproductionfactor_flag,
        productionactiveflag::number as productionactive_flag,

        -- temperatures
        templaterecordflag::number as templaterecord_flag,
        trim(tempstringforreports1)::varchar as tempstringforreports1,
        templaterecordused::number as templaterecordused,

        -- allocation factors
        computefactorflag::number as computefactor_flag,

        -- operational/equipment
        strokeline::float as strokeline,
        trim(pumperinstructions)::varchar as pumperinstructions,

        -- flags
        deleteflag::number as delete_flag,
        stateprodtaxreliefqualflag::number as stateprodtaxreliefqual_flag,
        computenetgasflag::number as computenetgas_flag,
        stripperqualifiedwellflag::number as stripperqualifiedwell_flag,
        tikoilsalesflag::number as tikoilsales_flag,
        calculationstatusflag::number as calculationstatus_flag,
        unitsconfigurableflag::number as unitsconfigurable_flag,
        riointerfaceflag::number as riointerface_flag,
        reportmanagementflag::number as reportmanagement_flag,
        statefilingflag::number as statefiling_flag,
        reportdrillingflag::number as reportdrilling_flag,
        transmitflag::number as transmit_flag,
        directionalwellflag::number as directionalwell_flag,
        hoursontotal24flag::number as hoursontotal24flag,
        insurancecountflag::number as insurancecount_flag,
        rioprodinterfaceflag::number as rioprodinterface_flag,
        allocmonthlydailyflag::number as allocmonthlydaily_flag,
        normalhandlingontaxflag::number as normalhandlingontax_flag,
        taxcreditqualifiedflag::number as taxcreditqualified_flag,
        allocautoflag::number as allocauto_flag,
        splitstreamflag::number as splitstream_flag,
        activeflag::number as active_flag,
        mmsfilingflag::number as mmsfiling_flag,
        gasbalancingflag::number as gasbalancing_flag,
        sealrequiredflag::number as sealrequired_flag,
        printflag::number as print_flag,
        tikgassalesflag::number as tikgassales_flag,
        allocationtypeflag::number as allocationtype_flag,
        hoursondefaultflag::number as hoursondefault_flag,
        reservescountflag::number as reservescount_flag,
        unitstypeflag::number as unitstype_flag,
        engineeringuploadflag::number as engineeringupload_flag,
        carryforwardflag::number as carryforward_flag,
        offshoreflag::number as offshore_flag,
        reportdeliverabilityflag::number as reportdeliverability_flag,
        accountinguploadflag::number as accountingupload_flag,
        marginalwellflag::number as marginalwell_flag,
        reportaccountingflag::number as reportaccounting_flag,

        -- audit/metadata
        trim(userstringb)::varchar as userstringb,
        trim(userstringe)::varchar as userstringe,
        usernumber4::float as usernumber4,
        usernumber2::float as usernumber2,
        trim(userstringc)::varchar as userstringc,
        trim(userstringf)::varchar as userstringf,
        usernumber5::float as usernumber5,
        userid::number as user_id,
        trim(userstringa)::varchar as userstringa,
        trim(userstringd)::varchar as userstringd,
        usernumber3::float as usernumber3,
        usernumber1::float as usernumber1,
        trim(usertimestamp)::varchar as user_timestamp,
        usernumber6::float as usernumber6,
        trim(rowuid)::varchar as rowu_id,
        _fivetran_deleted::boolean as _fivetran_deleted,
        _fivetran_synced::timestamp_tz as _fivetran_synced,

        -- other
        salescode::number as sales_code,
        trim(prunumber)::varchar as pru_number,
        trim(projectnumber)::varchar as project_number,
        lasttestgas::float as lasttestgas,
        trim(uicnumber)::varchar as uic_number,
        cumulativestartmonth::timestamp_ntz as cumulativestartmonth,
        trim(directionalsurveyreference)::varchar as directionalsurveyreference,
        trim(mmsleasenumber)::varchar as mmslease_number,
        acquisitioncode::number as acquisition_code,
        trim(systemmessage)::varchar as systemmessage,
        allocationruntwicemonthly::number as allocationruntwicemonthly,
        kellybushinglevel::float as kellybushinglevel,
        reservecatagory::number as reservecatagory,
        lasttestwater::float as lasttestwater,
        trim(comminglingnumber)::varchar as commingling_number,
        trim(blogictimestamp)::varchar as blogic_timestamp,
        mapcoordinatex::float as mapcoordinatex,
        allocationruntwicedaily::number as allocationruntwicedaily,
        prorationmeter::number as prorationmeter,
        ultimatereservesoil::float as ultimatereservesoil,
        trim(luwcode)::varchar as luw_code,
        commingledtype::number as commingled_type,
        lasttransmission::number as lasttransmission,
        datasourcecode::number as datasource_code,
        acreage::float as acreage,
        lasttestoil::float as lasttestoil,
        ultimatereserveswater::float as ultimatereserveswater,
        mapcoordinatey::float as mapcoordinatey,
        partnership::number as partnership,
        regulatoryproducttype::number as regulatoryproduct_type,
        trim(costcenter)::varchar as costcenter,
        averagejointlength::float as averagejointlength,
        locationorder::number as locationorder,
        gasanalysissourcetype::number as gasanalysissource_type,
        firstoilsales::timestamp_ntz as firstoilsales,
        firstgassales::timestamp_ntz as firstgassales,
        trim(mpscnumber)::varchar as mpsc_number,
        ultimatereservesgas::float as ultimatereservesgas,
        allocproductdependence::number as allocproductdependence

    from source

),

filtered as (

    select *
    from renamed
    where coalesce(_fivetran_deleted, false) = false
      and merrick_id is not null

),

enhanced as (

    select
        *,
        current_timestamp() as _loaded_at

    from filtered

),

final as (

    select
        -- identifiers
        merrick_id,
        allocationgroup_id,
        regsreservoir_id,
        country_id,
        location_merrick_id,
        operatorentity_id,
        county_id,
        outsideoperated_flag,
        formation_id,
        reservoir_id,
        statefiling_id,
        parametertemplate_id,
        division_id,
        production_id,
        accountingteam_id,
        facility_id,
        rioprod_id,
        regulatoryfield_id,
        battery_id,
        loadfluidsource_id,
        pumperperson_id,
        validationdaysback,
        plant_id,
        group_id,
        completionfluid_type,
        accounting_id,
        ihs_id,
        state_id,
        gathering_system_id,
        engineering_id,
        fieldgroup_id,
        area_id,
        rio_id,
        foremanperson_id,
        loadfluidsource_type,
        propertywell_id,
        reserveauditor_id,
        computeloadflu_id,
        dda_id,
        productionteam_id,
        gasanalysissource_id,
        lease_id,
        unit_id,
        wellview_id,
        injectiongatheringsystem_id,
        uwidisplay,
        operatorwell_id,
        engineerperson_id,
        accountantperson_id,
        scada_id,
        platform_id,
        superperson_id,
        drillingteam_id,
        route_id,
        petroregs_id,

        -- dates
        dateofinitialproductionoil,
        datewellsold,
        startactive_date,
        cleanupdatestamp,
        date_timestamp,
        endactive_date,
        allocautostart_date,
        datecompleted,
        recordcreation_date,
        lastproduction_date,
        dateofinitialproductiongas,
        blogic_date_stamp,
        lastload_date,
        datewellacquired,
        laststatuschanged_date,
        lastloadtime,
        cleanuptimestamp,
        dataeditstart_date,
        allocationtypestart_date,
        lasttest_date,
        dateshutin,
        rigrelease_date,
        user_date_stamp,
        dateabandoned,

        -- well/completion attributes
        producingstatus,
        completion_number,
        mmswell_name,
        well_name,
        uwisurface,
        completionstatus,
        mmsapiwell_number,
        thirdtodepth,
        lastproducingmethod,
        regulatorycompletion,
        thirdfromdepth,
        lastproducingstatus,
        completionflowdirection,
        uwi_type,
        uwisurfacedisplay,
        wellpluscompletion_name,
        uwi,
        todepth,
        completion_name,
        mmsproducinginterval,
        secondtodepth,
        completion_type,
        fromdepth,
        well_number,
        wellborediagramreference,
        packerdepth,
        apicompletion_number,
        producingmethod,
        secondfromdepth,
        apiwell_number,
        waterdepth,

        -- names and descriptions
        userstringflabel,
        accountingproperty_name,
        usernumber6label,
        jibproperty_name,
        userstringalabel,
        userdailynumber1label,
        userdailynumber2label,
        userstringblabel,
        userdailynumber3label,
        userdailynumber4label,
        userdailystringalabel,
        userstringclabel,
        setupcomments,
        usernumber1label,
        revenueproperty_name,
        accountingshort_name,
        commingleddescription,
        usernumber2label,
        userdailynumber5label,
        userdailystringblabel,
        userdailynumber6label,
        allocationdailycomment,
        usernumber3label,
        allocationmonthlycomment,
        userstringdlabel,
        usernumber4label,
        landproperty_name,
        userstringelabel,
        usernumber5label,

        -- geography
        latitude,
        statelease_name,
        stateproducingzone,
        stateapiwell_number,
        longitude,
        stateproperty_code,
        statedistrict_number,
        statewell_number,

        -- accounting/business entities
        operatorentityloc,
        property_number,

        -- volumes
        sigasvolconversion,
        reportproduction_flag,
        gasproductionfactor_flag,
        productionactive_flag,

        -- temperatures
        templaterecord_flag,
        tempstringforreports1,
        templaterecordused,

        -- allocation factors
        computefactor_flag,

        -- operational/equipment
        strokeline,
        pumperinstructions,

        -- flags
        delete_flag,
        stateprodtaxreliefqual_flag,
        computenetgas_flag,
        stripperqualifiedwell_flag,
        tikoilsales_flag,
        calculationstatus_flag,
        unitsconfigurable_flag,
        riointerface_flag,
        reportmanagement_flag,
        statefiling_flag,
        reportdrilling_flag,
        transmit_flag,
        directionalwell_flag,
        hoursontotal24flag,
        insurancecount_flag,
        rioprodinterface_flag,
        allocmonthlydaily_flag,
        normalhandlingontax_flag,
        taxcreditqualified_flag,
        allocauto_flag,
        splitstream_flag,
        active_flag,
        mmsfiling_flag,
        gasbalancing_flag,
        sealrequired_flag,
        print_flag,
        tikgassales_flag,
        allocationtype_flag,
        hoursondefault_flag,
        reservescount_flag,
        unitstype_flag,
        engineeringupload_flag,
        carryforward_flag,
        offshore_flag,
        reportdeliverability_flag,
        accountingupload_flag,
        marginalwell_flag,
        reportaccounting_flag,

        -- audit/metadata
        userstringb,
        userstringe,
        usernumber4,
        usernumber2,
        userstringc,
        userstringf,
        usernumber5,
        user_id,
        userstringa,
        userstringd,
        usernumber3,
        usernumber1,
        user_timestamp,
        usernumber6,
        rowu_id,
        _fivetran_deleted,
        _fivetran_synced,

        -- other
        sales_code,
        pru_number,
        project_number,
        lasttestgas,
        uic_number,
        cumulativestartmonth,
        directionalsurveyreference,
        mmslease_number,
        acquisition_code,
        systemmessage,
        allocationruntwicemonthly,
        kellybushinglevel,
        reservecatagory,
        lasttestwater,
        commingling_number,
        blogic_timestamp,
        mapcoordinatex,
        allocationruntwicedaily,
        prorationmeter,
        ultimatereservesoil,
        luw_code,
        commingled_type,
        lasttransmission,
        datasource_code,
        acreage,
        lasttestoil,
        ultimatereserveswater,
        mapcoordinatey,
        partnership,
        regulatoryproduct_type,
        costcenter,
        averagejointlength,
        locationorder,
        gasanalysissource_type,
        firstoilsales,
        firstgassales,
        mpsc_number,
        ultimatereservesgas,
        allocproductdependence,

        -- dbt metadata
        _loaded_at

    from enhanced

)

select * from final