version: 2

models:
  - name: wiserock_app__casing_components
    description: Wellview casing components data for Wise Rock application

  - name: wiserock_app__casing_run_tallies
    description: Wellview casing run tallies data for Wise Rock application

  - name: wiserock_app__casing_strings
    description: Wellview casing strings data for Wise Rock application

  - name: wiserock_app__companies
    description: Wellview company data for Wise Rock application

  - name: wiserock_app__completion_downtimes
    description: Wellview completion downtimes data for Wise Rock application

  - name: wiserock_app__completion_parameters
    description: Wellview completion parameters data for Wise Rock application

  - name: wiserock_app__completions
    description: Wellview completions data for Wise Rock application

  - name: wiserock_app__daily_allocations
    description: Wellview daily allocations data for Wise Rock application

  - name: wiserock_app__daily_costs
    description: Wellview daily costs data for Wise Rock application

  - name: wiserock_app__daily_forecasts
    description: Wellview daily forecasts data for Wise Rock application

  - name: wiserock_app__economic_projects
    description: Wellview economic projects data for Wise Rock application

  - name: wiserock_app__economic_scenarios
    description: Wellview economic scenarios data for Wise Rock application

  - name: wiserock_app__economics
    description: Wellview economics data for Wise Rock application

  - name: wiserock_app__fluid_levels
    description: Wellview fluid levels data for Wise Rock application

  - name: wiserock_app__forecast_parameters
    description: Wellview forecast parameters data for Wise Rock application

  - name: wiserock_app__job_afe_definitions
    description: Wellview job AFE definitions data for Wise Rock application

  - name: wiserock_app__job_reports
    description: Wellview job reports data for Wise Rock application

  - name: wiserock_app__job_time_log
    description: Wellview job time log data for Wise Rock application

  - name: wiserock_app__jobs
    description: Wellview jobs data for Wise Rock application

  - name: wiserock_app__production_tests
    description: Wellview production tests data for Wise Rock application

  - name: wiserock_app__prodview_system_integrations
    description: Wellview prodview system integrations data for Wise Rock application

  - name: wiserock_app__properties
    description: Wellview properties data for Wise Rock application

  - name: wiserock_app__remarks
    description: Wellview remarks data for Wise Rock application

  - name: wiserock_app__statuses
    description: Wellview statuses data for Wise Rock application

  - name: wiserock_app__tubing_component_mandrel_inserts
    description: Wellview tubing component mandrel inserts data for Wise Rock application

  - name: wiserock_app__tubing_component_mandrels
    description: Wellview tubing component mandrels data for Wise Rock application

  - name: wiserock_app__tubing_components
    description: Wellview tubing components data for Wise Rock application

  - name: wiserock_app__tubing_run_tallies
    description: Wellview tubing run tallies data for Wise Rock application

  - name: wiserock_app__tubing_strings
    description: Wellview tubing strings data for Wise Rock application

  - name: wiserock_app__units
    description: Wellview units data for Wise Rock application

  - name: wiserock_app__well_header
    description: Wellview well header data for Wise Rock application

  - name: wiserock_app__wellbore_directional_survey_data
    description: Wellview wellbore directional survey data for Wise Rock application

  - name: wiserock_app__wellbore_directional_surveys
    description: Wellview wellbore directional surveys data for Wise Rock application

  - name: wiserock_app__wellview_system_integrations
    description: Wellview system integrations data for Wise Rock application
